# Usa o padrão c1x: http://en.wikipedia.org/wiki/C11_%28C_standard_revision%29
CFLAGS=-Wall -g -std=c1x

# all: ex3 ex4 ex5 aluno alunos revisao programa
all: variavel_nao_inicializada operador_de_endereco usando_ponteiro

clean:
	rm -f variavel_nao_inicializada operador_de_endereco usando_ponteiro

