# Usa o padrão c1x: http://en.wikipedia.org/wiki/C11_%28C_standard_revision%29
CFLAGS+=-Wall -g -std=c1x

# all: ex3 ex4 ex5 aluno alunos revisao programa
all: aprendendo_printf

clean:
	rm -f aprendendo_printf

