CC=gcc
CFLAGS=-Wall -g -std=c1x

all: abrindo_arquivo_de_texto abrindo_arquivo_binario_para_escrita fechando_arquivo lendo_e_escrevendo_char

clean:
	rm -rf abrindo_arquivo_de_texto abrindo_arquivo_binario_para_escrita fechando_arquivo lendo_e_escrevendo_char

