# Usa o padrão c1x: http://en.wikipedia.org/wiki/C11_%28C_standard_revision%29
CFLAGS+=-Wall -g -std=c1x

# all: ex3 ex4 ex5 aluno alunos revisao programa
all: tamanho_dos_tipos do_while_exemplo helloworld while_exemplo matriz estrutura_sequencial decisao_simples decisao_composta decisao_multipla programa_completo cpf_formatado

clean:
	rm -f tamanho_dos_tipos do_while_exemplo helloworld while_exemplo matriz estrutura_sequencial decisao_simples decisao_composta decisao_multipla programa_completo cpf_formatado

