=== Atividades

TIP: Na sala de aula, nos fóruns e mensagens recomendamos a utilização do site https://gist.github.com para compartilhar códigos e tirar dúvidas sobre eles.

1. *Entendo a necessidade dos registros.* Nós poderíamos escrever os programas
sem utilizar registros. Qual a utilidade de se utilizar registros nos programas?

2. O que é um campo *identificador*? Dê exemplos *não* contidos neste capítulo.

3. Na <<sec_registro_analise>> analisamos diversas situações buscando os campos
necessários para criação de Registros. Agora chegou a sua vez de fazer o 
mesmo. Para cada situação a seguir:
+
--
* Defina o(s) *nome(s)* do tipo de registro que você criará
* Especifique os *campos* com seus respectivos *tipos*
* Indique quais são os campos *identificadores*, caso exista
* Escreva as *declarações* do(s) Registro(s) em C
--

.. Um programa para registrar os animais e os clientes de um Petshop.
.. Um programa para registrar e consultar filmes.
.. Um programa para uma biblioteca registrar os seus livros.
.. Um programa para agendar e consultar compromissos. {solucao}

4. *Pratique o uso de registros*. Utilizando os registros definidos no
capítulo, faça pequenos programas e teste com as entradas indicadas.footnote:[Testar 
com valores pré-definidos facilita o desenvolvimento dos programas, 
faça disso um hábito. Veremos mais adiante como redirecionar a entrada
do programa, facilitando ainda mais os testes.]
+
--
.. Utilizando o <<ex_reg_aluno>>, faça um programa que indique
a situação de cada Aluno: *Aprovado*, se média das notas for maior ou igual 5;
*Reprovado* se a média for inferior a 5; *Aprovado com menção de honra* se
média for superior ou igual a 9.
+
--
.Entrada: nome matrícula nota1 nota2
----
include::code/cap2/exercicio_aluno.data[]
----
--

.. Utilizando o <<ex_reg_pessoa>>, escreva um programa que imprima o
IMC das mulheres, depois o dos homens. Quando imprimir o IMC, exiba uma mensagem
indicando a condição em que a pessoa se encontra, de acordo com a tabela a seguir.
+
[width="85%",cols="2,3",frame="topbot",options="header"]
|====
| IMC               | Classificação
| abaixo de 18,5    | Subnutrido ou abaixo do peso
| entre 18,6 e 24,9 | Peso ideal (parabéns)
| entre 25,0 e 29,9 | Levemente acima do peso
| entre 30,0 e 34,9 | Primeiro grau de obesidade
| entre 35,0 e 39,9 | Segundo grau de obesidade
| acima de 40       | Obesidade mórbida
|====
+
--
.Entrada: nome altura peso cpf sexo
----
include::code/cap2/exercicio_pessoa.data[]
----
--

.. Utilizando o <<ex_reg_ponto>>, escreva um programa que leia alguns
pontos, indicando em qual quadrante eles estão no plano cartesiano.
+
--
.Entrada: p1.x p1.y p2.x p2.y p3.x p3.y
----
include::code/cap2/exercicio_ponto.data[]
----
--

.. Utilizando o <<ex_reg_produto>>, escreva um programa que cadastra
uma lista de produtos. Em seguida imprima os produtos ordenadamente pelo
menor preço.
+
--
.Entrada: codigo nome valor
----
include::code/cap2/exercicio_produto.data[]
----
--
--

5. *Criando novos Registros*. Agora que você já praticou a utilização de
Registro está no momento de criar os seus próprios Registros.
+
[IMPORTANT]
====
As questões a seguir *não* especificam os programas minuciosamente, elas foram 
elaboradas assim para permitir que você expresse a sua criatividade. 
No entanto, você deve:

* Resolver as questões utilizando os conhecimentos adquiridos neste capítulo
* Utilizar composição de registros quando for apropriado
* Preparar valores de entradas fixos para o seu programa, de forma a testá-lo
eficientemente.

====

.. Faça um programa para um Petshop, para cadastrar os clientes da loja e 
seus animais. O programa deve possibilitar pesquisa pelo cliente ou pelo
seu animal.

.. Faça um programa para gerenciar os gastos pessoais. O programa deve poder
registrar os gastos por categoria e emitir um relatório para proporcionar
um controle financeiro.

.. Faça um programa para registrar os filmes que você assistiu ou quer assistir.
Os filmes devem ser cadastrados por categorias. O programa deve emitir listas
de filmes com base em dois critérios à sua escolha.

.. Faça um programa para auxiliar a Policia Federal acompanhar as explosões de
caixas eletrônicos ao longo do tempo. Após cadastrar as explosões, o sistema
deve informar as regiões críticas.

.. Faça um programa para simular um dicionário. Ele deve cadastrar algumas
palavras e possibilitar alguma forma de navegação. Consulte um dicionário real
para verificar que além do significado da palavra, outras informações diferentes
também são cadastradas.

////
Sempre terminar o arquivo com uma nova linha.
////

