=== Atividades

1. Faça um algoritmo que receba um número positivo e maior que zero, calcule e mostre: o número 
digitado ao quadrado, o número digitado ao cubo e a raiz quadrada do número digitado.

2. Analise o algoritmo abaixo e explique o que ele faz. Quais são os
  valores de `LUCROMAX`, `PREÇOMAX` e `INGRESSOSMAX` que serão
  impressos no final da execução do algoritmo?
+
[source,c,numbered]
----
Algoritmo
  declare PREÇO, //preço do ingresso em Reais
    INGRESSOS, //número provável de ingressos vendidos
    DESPESAS, //despesas com o espetáculo
    LUCRO, //lucro provável
    LUCROMAX, //lucro máximo provável
    PREÇOMAX, //preço máximo
    INGRESSOSMAX: numérico; //número máximo de ingressos vendidos
  LUCROMAX ← 0;
  PREÇO ← 5;
  INGRESSOS ← 120;
  DESPESAS ← 200;
  Enquanto (PREÇO > 1) {
    LUCRO ← INGRESSOS*PREÇO – DESPESAS;
    imprima LUCRO, PREÇO;
    se (LUCRO ← LUCROMAX) {
      LUCROMAX ← LUCRO;
      PREÇOMAX ← PREÇO;
      INGRESSOSMAX ← INGRESSOS;
    }
    INGRESSOS ← INGRESSOS + 26;
    PREÇO ← PREÇO – 0,5;
  }
  imprima LUCROMAX, PREÇOMAX, INGRESSOSMAX;
fim algoritmo

----


3. Analise o código abaixo e diga qual é o valor que a variável `S` terá ao final da 
execução do algoritmo.
+
----
Algoritmo
  declare fim, i, j, x, exp, num_ter, den, D, fat, S: numérico;
  num_ter = 3;
  x = 3;
  S = 0;
  D = 1;
  para (i=1; i<= num_ter; i=i+1) {
    fim = D;
    fat = 1;
    para (j=1; j<= fim; j=j+1) {
      fat = fat*j;
    }
    exp = i+1;
    se (RESTO(exp/2) == 0){
      S = S-(x^(exp))/fat;
    }
    senão{
      S = S + (x^(exp))/fat;
    }
    se (D == 4){
      den = -1;
    }
    se (D==1){
      den = 1;
    }
    se (den == 1){
      D = D +1;
    }
    senão{
      D = D – 1;
    }
  }
  imprima S;
fim algoritmo
----

4. Faça um programa que leia um CPF, salve-o numa variável do tipo
  `long long` e em seguida imprima o CPF lido. {resposta}

5. Faça um programa em C que receba o ano de nascimento de uma pessoa e o ano atual, calcule e 
mostre: (a) a idade da pessoa; e (b) quantos anos ela terá em 2045. O programa deve ser capaz de 
receber somente valores positivos e maiores do que zero para a idade da pessoa.


6. Um supermercado deseja reajustar os preços de seus produtos usando o seguinte critério: o 
produto poderá ter seu preço aumentado ou diminuído. Para o preço ser alterado (ou seja, ser 
aumentado ou diminuído), o produto deve atender *PELO MENOS* uma das linhas da tabela a seguir:
+
--
[cols="^3,^2,^1,^1",frame="topbot",options="header"]
|====
| Venda média mensal (unidades vendidas)|Preço atual (R$)|% de aumento|% de diminuição
| Menor que 500 | < R$ 30,00|10 %| -
| Entre 500 (inclusive) e 1200| > = R$ 30,00 e < R$ 80,00| 15 %| -
| Igual ou maior que 1200| > = R$ 80,00|- | 20 %
|====

Faça um programa em C que receba o preço atual e a venda média mensal do produto, calcule e 
mostre o novo preço.
--


7. João Papo-de-Pescador está organizando uma corrida de automóveis e precisa de um método para 
computar os tempos das voltas no circuito. Faça um programa em C que tenha como entrada: i) o número 
de pilotos que disputarão a corrida; ii)  os seus respectivos nomes; iii) o número de voltas da 
corrida; iv) e o tempo de todas as voltas para cada piloto. O programa deve imprimir no final o 
tempo médio da volta para cada piloto e o tempo da volta mais rápida da corrida (ou seja, a volta 
que foi feita no menor tempo) e qual foi o piloto que a fez.



8. Em uma competição de ginástica olímpica, a nota é determinada por um painel de seis juízes. 
Cada um dos juízes atribui uma nota entre zero e dez para o desempenho do atleta. Para calcular a 
nota final, a nota mais alta e a nota mais baixa são descartadas e é calculada a média das 
quatro notas restantes. Escreva um programa que leia seis notas que devem estar entre zero e dez e, 
em seguida, calcule a média após o descarte da maior e da menor nota. Faça duas versões desse 
programa em C: i) usando somente estruturas de seleção e de repetição e sem o uso de vetores; ii) com o uso de vetores e estruturas de seleção e repetição.





9. Uma empresa decidiu dar uma gratificação de Natal a seus funcionários baseada no número de 
horas extras e no número de horas que o funcionário faltou ao trabalho. Faça um programa em C 
que calcule o valor da gratificação de Natal. O valor do prêmio é obtido pela consulta à 
tabela que se segue, na qual a variável SH é calculada da seguinte forma: SH = número de horas 
extras – 0,5*(número de horas faltadas).
+
--
[width="80%",cols="^2,^1",frame="topbot",options="header"]
|====
| SH (em minutos)|Gratificação (em R$)
| Maior ou igual a 2200|600,00
| Entre 1700 (inclusive) e 2200|500,00
| Entre 1000 (inclusive) e 1700|400,00
| Entre 500 (inclusive) e 1000|300,00
| Menor que 500|200,00
|====
--


10. Analise o código abaixo e diga qual é o valor que a variável `E` terá ao final da 
execução do programa.
+
[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  double fat, E;
  int i, j, n;
  n = 4;
  for(i=1; i<=n; i++){
    fat=1;
    for(j=1; j<=n; j++){
      fat=fat*j;
    }
    E=E+(1/fat);
  }
  printf ("O valor da variável E é %lf ", E);
  return 0;
}
----


11. Faça um programa em C que receba o salário de um funcionário e, usando a tabela a seguir, 
calcule e mostre o seu novo salário. O programa deve aceitar somente valores positivos e maiores 
do que zero para o salário do funcionário.
+
--
[width="80%",cols="^2,^1",frame="topbot",options="header"]
|====
| Faixa Salarial|% de aumento
| Até R$ 500,00|55 %
| Entre R$ 500,00 e 700,00 (inclusive)|45 %
| Entre R$ 700,00 e 900,00 (inclusive)|35 %
| Entre R$ 900,00 e 1100,00 (inclusive)|25 %
| Entre R$ 1100,00 e 1300,00 (inclusive)|15%
| Acima de R$ 1300,00|5%
|====
--

12. Uma agência bancária possui vários clientes que podem fazer investimentos com rendimentos 
mensais conforme a tabela a seguir:
+
--
[width="90%",cols="^1m,^2,^1",frame="topbot",options="header"]
|====
| Código do tipo de investimento|Nome|Rendimento mensal %
| 1|Poupança|0,6 %
| 2|Poupança plus|1,1 %
| 3|Fundos de renda fixa|1,8 %
| 4|Fundos de renda variável|2,5 %
|====

Faça um programa em C que tenha como dados de entrada o código do cliente, o código do tipo de 
investimento e o valor investido. O programa deve calcular e imprimir o rendimento mensal de 
acordo com o tipo de investimento do cliente. No final, deverá imprimir o total 
investido por todos os clientes consultados e o somatório do rendimento mensal pago a todos os 
clientes consultados. A leitura de clientes pelo programa terminará quando o código do cliente 
digitado for menor ou igual a `0` (zero).
--

////
Sempre terminar o arquivo com uma nova linha.
////

