[[cap_bases_legais]]
== Base Legal do Curso de Licenciatura em Computação a Distância

Antes de apresentarmos uma proposta de trabalho para o nosso curso,
precisamos primeiro compreendermos o contexto em que ele está
inserido e suas bases legais. 


[[sec_finalidades]]
=== Finalidades da Educação Superior

(((Educação Superior, Finalidades)))
(((LDB)))


A Lei de Diretrizes e Bases da Educação Nacional (LDB) define as
finalidades da Educação Superior no Art 43°:

I) estimular a criação cultural e o desenvolvimento do espírito
científico e do pensamento reflexivo;
II) formar diplomados nas diferentes áreas de conhecimento, aptos
para a inserção em setores profissionais e para a participação no
desenvolvimento da sociedade brasileira, e colaborar na sua formação
contínua;
III) incentivar o trabalho de pesquisa e investigação científica,
visando o desenvolvimento da ciência e da tecnologia e da criação e
difusão da cultura, e, desse modo, desenvolver o entendimento do homem
e do meio em que vive;
IV) promover a divulgação de conhecimentos culturais, científicos e
técnicos que constituem patrimônio da humanidade e comunicar o saber
através do ensino, de publicações ou de outras formas de comunicação;
V) suscitar o desejo permanente de aperfeiçoamento cultural e
profissional e possibilitar a correspondente concretização, integrando
os conhecimentos que vão sendo adquiridos numa estrutura intelectual
sistematizadora do conhecimento de cada geração;
VI) estimular o conhecimento dos problemas do mundo presente, em
particular os nacionais e regionais, prestar serviços especializados à
comunidade e estabelecer com esta uma relação de reciprocidade;
VII) promover a extensão, aberta à participação da população, visando
à difusão das conquistas e benefícios resultantes da criação cultural
e da pesquisa científica e tecnológica geradas na instituição.

Qualquer proposta de trabalho no ensino superior deve está
subordinada a este artigo.

TIP: A LDB pode ser baixada em
http://portal.mec.gov.br/arquivos/pdf/ldb.pdf.


=== Diretrizes Curriculares Nacionais para os cursos de graduação em Computação

TIP: Documento pode ser acessado em
http://portal.mec.gov.br/index.php?option=com_docman&task=doc_download&gid=11205.


[[sec_metodologia]]
==== Da Metodologia de Ensino
 
A metodologia de ensino deve ser
centrada no aluno como sujeito da aprendizagem e apoiada no professor
como facilitador do processo de ensino-aprendizagem. O professor deve
fortalecer o trabalho extraclasse como forma de o aluno aprender a
resolver problemas, aprender a aprender, tornar-se independente e
criativo. O professor deve mostrar, ainda, as aplicações dos conteúdos
teóricos, ser um mediador, estimular a competição, a comunicação,
provocar a realização de trabalho em equipe, motivar os alunos para os
estudos e orientar o raciocínio e desenvolver as capacidades de
comunicação e de negociação. O projeto pedagógico deve prever o
emprego de metodologias de ensino e aprendizagem que promovam a
explicitação das relações entre os conteúdos abordados e as
competências previstas para o egresso do curso. A metodologia de
ensino deve desenvolver uma visão sistêmica para resolução de
problemas.

[[sec_perfil_egresso]]
==== Perfil de Egresso
(((Perfil de Egresso)))

IMPORTANT: Nas seções a seguir apresentamos o Perfil de Egresso do Curso de
*Licenciatura em Computação*, não confundir com o Curso de *Bacharelado
em Computação*.

Os cursos de *bacharelado* e de *licenciatura* da área de Computação devem
assegurar a formação de profissionais dotados:

1. Do conhecimento das questões sociais, profissionais, legais,
   éticas, políticas e humanísticas;

2. Da compreensão do impacto da computação e suas tecnologias na
   sociedade no que concerne ao atendimento e à antecipação
   estratégica das necessidades da sociedade;

3. Da visão crítica e criativa na identificação e resolução de
   problemas contribuindo para o desenvolvimento de sua área;

4. Da capacidade de atuar de forma empreendedora, abrangente e
   cooperativa no atendimento às demandas sociais da região onde atua,
   do Brasil e do mundo;

5. Da capacidade de utilizar racionalmente os recursos disponíveis de
   forma transdisciplinar;

6. Da compreensão das necessidades da contínua atualização e
   aprimoramento de suas competências e habilidades;

7. Da capacidade de reconhecer a importância do pensamento
   computacional na vida cotidiana, como também sua aplicação em
   outros domínios e ser capaz de aplicá-lo em circunstâncias
   apropriadas; e

8. Da capacidade de atuar em um mundo globalizado do trabalho.

Levando em consideração a flexibilidade necessária para atender
domínios diversificados de aplicação e as vocações institucionais,
espera-se que os egressos dos cursos de *licenciatura em Computação*,
além de atenderem ao perfil geral previsto para os egressos dos cursos
de Formação de Professores para a Educação Básica, estabelecido por
meio da Resolução CNE/CP no 1/2002:

1. Possuam sólida formação em Ciência da Computação, Matemática e
   Educação visando ao ensino de Ciência da Computação nos níveis da
   Educação Básica e Técnico e suas modalidades e a formação de
   usuários da infraestrutura de software dos Computadores, nas
   organizações;

2. Possuam capacidade de fazer uso da interdisciplinaridade e
   introduzir conceitos pedagógicos no desenvolvimento de Tecnologias
   Educacionais, permitindo uma interação humano-computador
   inteligente, visando o ensino-aprendizagem assistidos por
   computador, bem como nas interações de educação à distância;

3. Possuam capacidade de atuar como docente, estimulando a
   investigação científica com visão de avaliação crítica e reflexiva;

4. Sejam capazes de atuar no desenvolvimento de processos de
   orientação, motivação e estimulação da aprendizagem, com a seleção
   de plataformas computacionais adequadas às necessidades das
   organizações;

// ===== Perfil referenciado
// TODO: Formação de Professores para a Educação Básica

[[sec_competencias]]
==== Competências e Habilidades

Os cursos de *bacharelado* e de *licenciatura* em Computação devem formar
profissionais que revelem pelo menos as competências e habilidades
comuns para:

1. Identificar problemas que tenham solução algorítmica;

2. Conhecer os limites da computação;

3. Resolver problemas usando ambientes de programação;

4. Tomar decisões e inovar, com base no conhecimento do funcionamento
   e das características técnicas de hardware e da infraestrutura de
   software dos sistemas de computação consciente dos aspectos éticos,
   legais e dos impactos ambientais decorrentes;

5. Compreender e explicar as dimensões quantitativas de um problema;

6. Gerir a sua própria aprendizagem e desenvolvimento, incluindo a
   gestão de tempo e competências organizacionais;

7. Preparar e apresentar seus trabalhos e problemas técnicos e suas
   soluções para audiências diversas, em formatos apropriados (oral e
   escrito);

8. Avaliar criticamente projetos de sistemas de computação;

9. Adequar-se rapidamente às mudanças tecnológicas e aos novos
   ambientes de trabalho;

10. Ler textos técnicos na língua inglesa;

11. Empreender e exercer liderança, coordenação e supervisão na sua
    área de atuação profissional;

12. Ser capaz de realizar trabalho cooperativo e entender a força que
    dele pode ser derivada


Levando em consideração a flexibilidade necessária para atender
domínios diversificados de aplicação e as vocações institucionais, os
cursos de *licenciatura* em Computação devem prover uma formação
profissional que revele, pelo menos, as habilidades e competências
para:

1. Especificar os requisitos pedagógicos na interação
   humano-computador;

2. Especificar e avaliar softwares e equipamentos para aplicações
   educacionais e em Educação à Distância;

3. Projetar e desenvolver softwares e hardware educacionais e para
   Educação à Distância em equipes interdisciplinares;

4. Atuar junto ao corpo docente das Escolas nos níveis da Educação
   Básica e Técnico e suas modalidades e demais organizações no uso
   efetivo e adequado das tecnologias da educação;

5. Produzir materiais didáticos com a utilização de recursos
   computacionais, propiciando inovações nos produtos, processos e
   metodologias de ensino aprendizagem;

6. Administrar laboratórios de informática para fins educacionais;

7. Atuar como agentes integradores promovendo a acessibilidade
   digital;

8. Atuar como docente com a visão de avaliação crítica e reflexiva;

9. Propor, coordenar e avaliar, projetos de ensino-aprendizagem
   assistidos por computador que propiciem a pesquisa.

[[sec_curriculo]]
==== Conteúdos Curriculares

Os conteúdos tecnológicos e básicos comuns a todos os cursos são:
sistemas operacionais; compiladores; engenharia de software; interação
humano-computador; redes de computadores; sistemas de tempo real;
inteligência artificial e computacional; processamento de imagens;
computação gráfica; banco de dados; dependabilidade; segurança;
multimídia; sistemas embarcados; processamento paralelo; processamento
distribuído; robótica; realidade virtual; automação; novos paradigmas
de computação; matemática discreta; estruturas algébricas; matemática
do contínuo [cálculo, álgebra linear, equações diferenciais, geometria
analítica; matemática aplicada (séries, transformadas), cálculo
numérico]; teoria dos grafos; análise combinatória; probabilidade e
estatística; pesquisa operacional e otimização; teoria da computação;
lógica; algoritmos e complexidade; linguagens formais e autômatos;
abstração e estruturas de dados; fundamentos de linguagens (sintaxe,
semântica e modelos); programação; modelagem computacional; métodos
formais; análise, especificação, verificação e testes de sistemas;
circuitos digitais; arquitetura e organização de computadores;
avaliação de desempenho; ética e legislação; empreendedorismo;
computação e sociedade; filosofia; metodologia cientifica; meio
ambiente; fundamentos de administração; fundamentos de economia.

Os conteúdos básicos e tecnológicos, específicos para os cursos de
*licenciatura* em Computação, são os seguintes: educação assistida por
computador; estudo e desenvolvimento de tecnologias computacionais
aplicadas à educação; adaptação e personalização de sistemas de
avaliação de aprendizagem assistidas por computador; produção de
materiais instrucionais; aprendizagem colaborativa assistida por
computador; ambientes virtuais de aprendizagem; arquiteturas de
software educativo; avaliação de software e hardware educativo;
inteligência artificial aplicada à educação; métodos e padrões para
artefatos educacionais; métodos e processos de engenharia de software
aplicados ao desenvolvimento de ambientes educacionais; modelagem
cognitiva aplicada à educação; suporte computacional à aprendizagem
organizacional; tecnologias wireless, móvel e ubíqua para a
aprendizagem; interação humano- computador de software educativo; web
semântica e ontologias na educação; métricas de métodos e técnicas de
educação assistida por computador; teorias da aprendizagem e do
desenvolvimento humano; didática para o ensino de computação;
filosofia da educação, sociologia da educação; organização e sistemas
educacionais, psicologia da aprendizagem; libras; educação à
distância; avaliação da aprendizagem.

IMPORTANT: Para a *licenciatura* deverão ser incluídos conteúdos de formação
pedagógica, considerando as Diretrizes Curriculares Nacionais para a
formação de professores para a Educação Básica.


[[sec_atividades_complementares]]
==== Atividades Complementares
As atividades complementares são componentes curriculares que têm como
objetivo principal enriquecer expandir o perfil do egresso com
atividades que privilegiem aspectos diversos da sua formação,
incluindo atividades desenvolvidas fora do ambiente acadêmico.  Tais
atividades constituem instrumental importante para o desenvolvimento
pleno do aluno, servindo de estímulo a uma formação prática
independente e interdisciplinar, sobretudo nas relações com o mundo do
trabalho. Tais atividades podem ser cumpridas em diversos ambientes,
como a instituição a que o estudante está vinculado, outras
instituições e variados ambientes sociais, técnico-científicos ou
profissionais, em modalidades tais como: formação profissional (cursos
de formação profissional, experiências de trabalho ou estágios não
obrigatórios), de extensão universitária junto à comunidade, de
pesquisa (iniciação científica e participação em eventos
técnico-científicos, publicações científicas), de ensino (programas de
monitoria e tutoria ou disciplinas de outras áreas), políticas
(representação discente em comissões e comitês) e de empreendedorismo
e inovação (participação em Empresas Júnior, incubadores ou outros
mecanismos). Estas e outras atividades com as características
mencionadas devem ser permanentemente incentivadas no cotidiano
acadêmico, permitindo a diversificação das atividades complementares
desenvolvidas pelos estudantes.

[[sec_acompanhamento_avaliacao_do_curso]]
==== Acompanhamento e avaliação 
O acompanhamento dos cursos deve ser contínuo, podendo se basear em
autoavaliação e no relato das experiências de seus egressos. Espera-se
que os egressos dos cursos tenham os perfis, as competências, as
habilidades e as atitudes estabelecidos pelas Instituições de Educação
Superior, com base nessas Diretrizes. Deve-se compreender que os
recém-egressos dos cursos, geralmente, têm formação profissional ainda
incipiente. A profissionalização plena vem com o tempo, podendo levar
anos, após a realização de diversas atividades na profissão,
normalmente acompanhadas por um profissional sênior. Assim, o processo
de avaliação dos cursos pode ser realimentado com informações
relevantes sobre o desempenho nas atividades laborais ou por meio da
comparação com egressos de mesmo perfil, de outras instituições.

[[sec_qualidade]]
=== Referenciais de Qualidade para Educação Superior a Distância

Outro documento importante é o ``Referenciais de Qualidade para
Educação Superior a Distância'', ele aborda diversos aspectos
do curso como: 

i) Concepção de educação e currículo no processo de ensino e
aprendizagem; 

ii) Sistemas de Comunicação; 

iii) Material didático; 

iv) Avaliação; 

v) Equipe multidisciplinar; 

vi) Infra-estrutura de apoio;

vii) Gestão Acadêmico-Administrativa; 

viii) Sustentabilidade financeira.


TIP: Você pode encontrar o documento em:
http://portal.mec.gov.br/seed/arquivos/pdf/legislacao/refead1.pdf

[[sec_ppc]]
=== Projeto Pedagógico do Curso - PPC
(((PPC)))

Todos os cursos possuem um PPC, que devem nortear a execução do curso.
Conheça o seu!

TIP: PPC do Curso de Licenciatura em Computação a Distância na UFPB: 
http://portal.virtual.ufpb.br/wordpress/wp-content/uploads/2013/01/PPC-Licenciatura-Computa%C3%A7%C3%A3o-UFPB-Versao-Final-06082012.pdf





incentivar nossos alunos a buscarem financiamentos para execuções de
projetos nas disciplinas.  que possam ser aproveitados nas disciplinas
que estão cursando na universidade.



=== Premissas

// http://developer.ubuntu.com/resources/programming-languages/c-and-c-plus-plus/
// http://www.codeblocks.org/

Instalar o codeblocks:
    
    sudo apt-get install codeblocks

Fazer um experimento, que ao descrevê-lo fique evidente o pensamento
empirista, adaptando o experimento para torná-lo empirista.

Pensar num experimento que possamos nos apropriar dos conhecimentos
de cálculo ou matemática elementar.

Fazer um programa em C para resolvê-lo.

Se o problema fizer parte do dia-a-dia dos alunos, melhor ainda.

Problema deve ser realizado por um grupo, no mínimo uma dupla.

Deverá demonstrar a utilização dos compiladores, do git para
compartilhar o código entre eles. Demonstrar a diferença de cultura de
cultura entre eles.


.Problemas
* Contrução de um problema para controlar as cadernetas


.Problemas que incomodam
* Não receber o salário em dia
* Receber informações em cima da hora, sobre assuntos que eram de
  conhecimento de todos. (Em outras palavras: ser o último a saber).
* Preenchimento de caderneta em papel, ao invés do digital
** Como incorporar assuntos de outras disciplinas?
** Metodologia do trabalho / Publicando um artigo com o projeto?
** Cálculo: Análise das notas? Das Presenças? Como utilizar funções?
Funções injetoras? função inversa? Limites? Continuidade? Derivada?
Reta tangente? Valor médio? Integral?
** Inglês: escrita do abstract? Escrita da documentação e aplicação em
ingles?
** Fundamentação Psicológica da Educação: Analisar o conhecimento
obtido durante o projeto pelos integrantes? Artigo?

Analisar as repercursões do uso do programa. Fases do desenvolvimento:
análise, desenvolvimento e deploy.

Projeto para analisar o dados dos alunos?
Utilizar o github para juntar os dados de forma distribuída.
Desenhar gráficos? Usar o `dot` ou outra ferramenta para desenho?

Google API?


