[appendix]
== Bibliotecas

:online: {gitrepo}/blob/master/livro/capitulos/code/bibliotecas
:local: code/bibliotecas

[[c1x]]
=== Padrão C1X da Linguagem C

O último padrão adotado para a Linguagem C foi publicado pela ISO em
12/8/2011 no documento: ISO/IEC 9899:2011. Este padrão é conhecido
como C11 ou C1X, você pode consultar gratuitamente a última versão
pública do documento em:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf.

NOTE: Durante o livro iremos referenciar este documento apenas por
``Padrão C1X''.

IMPORTANT: Nas seções a seguir nós resumimos a documentação das
funções e bibliotecas utilizadas neste livro. No entanto, nós
recomendamos a consulta da documentação original (em inglês).


[id="sec_main",reftext="main()"]
=== main()

(((main)))

TODO: Explicar os parâmetros da função `main`.

[id="assert_h",reftext="assert.h"]
=== assert.h

(((assert.h)))

TIP: Mais informações sobre esta função pode ser consultada na seção
``7.2 Diagnostics <assert.h>'' no padrão C1X da linguagem C. Os
seguintes sites também podem ajudá-lo a compreender esta função:
http://www.acm.uiuc.edu/webmonkeys/book/c_guide/2.1.html,
http://pt.wikipedia.org/wiki/Assert.h e
http://www.cplusplus.com/reference/cassert/assert/.



[id="assert", reftext="assert()"]
==== assert()

(((assert)))

[source,c]
----
void assert ( int expressao )
----

Esta função costuma ser utilizado

[[TIP]]
====
Ajuda online:
http://www.cplusplus.com/reference/cassert/assert/

====

[id="stdlib_h",reftext="stdlib.h"]
=== stdlib.h

(((stdlib.h)))

[id="exit",reftext="exit()"]
==== exit()

(((exit)))

[source,c]
----
void exit( int codigoDeErro )
----

Termina o programa indicando o código de erro. Ver os códigos de erro
<<EXIT_SUCCESS>> e <<EXIT_FAILURE>>.


[id="EXIT_SUCCESS",reftext="EXIT_SUCCESS"]
==== EXIT_SUCCESS

(((EXIT_SUCCESS)))

Constante para indicar que não houve erro.

[id="EXIT_FAILURE",reftext="EXIT_FAILURE"]
==== EXIT_FAILURE

(((EXIT_FAILURE)))

Constante para indicar que houve erro na execução do arquivo.


==== Gerência de memória

[id="malloc", reftext="malloc()"]
===== malloc()

(((malloc)))

[source,c]
----
#include <stdlib.h>
void *malloc(size_t tamanho);
----

////

The malloc function allocates space for an object whose size is specified by size and
whose value is indeterminate.

The malloc function returns either a null pointer or a pointer to the allocated space.
////

Aloca um espaço de `tamanho` bytes, o conteúdo do espaço alocado é
indefinido.

Retorna `NULL` se houve erro na alocação ou um ponteiro para o espaço
alocado.


[id="calloc", reftext="calloc()"]
===== calloc()

(((calloc)))

[source,c]
----
void *calloc(size_t quantidade, size_t tamanho);
----

A função `calloc`, além de alocar espaço na memória, inicializa todo o
espaço alocado com `0` (zeros). 

[id="free", reftext="free()"]
===== free()

(((free)))

[source,c]
----
void free(void *ponteiro);
----

A função `free` causa a desalocação do ponteiro. Se `ponteiro` for
`NULL` nada acontece. Se `ponteiro` não for um ponteiro válido ou já
foi desalocado anteriormente, o comportamento não é definido.



[id="realloc", reftext="realloc()"]
===== realloc()

(((realloc)))

[source,c]
----
void *realloc(void *ponteiro, size_t tamanho);
----

Desaloca `ponteiro` e aloca um novo espaço com o tamanha especificado
por `tamanho`.

[id="string_h", reftext="string.h"]
=== string.h

(((string.h)))

// TODO: funçõe de string.

[id="strlen", reftext="strlen()"]
==== strlen()

(((strlen)))

[source,c]
----
size_t strlen(const char *string);
----

Computa o tamanho de um string.

Retorna tamanho do string, até encontrar o carácter `\0`.

[id="strcmp", reftext="strcmp()"]
==== strcmp()

(((strcmp)))

[source,c]
----
int strcmp(const char *primeiroString, const char *segundoString);
----

Compara dois strings.

Retorna um valor maior do que zero se `primeiroString >
segundoString`, zero se `primeiroString==segundoString` e um valor
negativo de `primeiroString<segundoString`.


[id="strncmp", reftext="strncmp()"]
==== strncmp()

(((strncmp)))

[source,c]
----
int strncmp(const char *primeiroString, 
    const char *segundoString, size_t n);
----

Compara dois strings até `n` posições.

[id="strcpy", reftext="strcpy()"]
==== strcpy()

(((strcpy)))

[source,c]
----
char *strcpy(char * destino, const char * origem);
----

Copia o conteúdo de um string para outro.

A função retorna `destino`.


[id="strncpy", reftext="strncpy()"]
==== strncpy()

(((strncpy)))

[source,c]
----
char *strcpy(char * destino, const char * origem,
    size_t n);
----

Copia o conteúdo de `origem` para `destino` até no máximo `n`
carácteres.

A função retorna `origem`.


[id="stdbool_h", reftext="stdbool.h"]
=== stdbool.h

(((stdbool.h)))

Inclusão da biblioteca <<stdbool_h>>, que define o tipo `bool`. Este
tipo pode ser utilizado como retorno de expressões lógicas. Além disso
também estão definidos macro `true` com o valor `1` e `false` com o
valor `0`.

[id="stdio_h", reftext="stdio.h"]
=== stdio.h

(((stdio.h)))

NOTE: A documentação sobre as funções de leitura de arquivo estão 
contidas na seção ``7.21 Input/output <stdio.h>'' do padrão C1X.

[id="fopen", reftext="fopen()"]
==== fopen()

(((fopen)))

[source,c]
----
#include <stdio.h>
FILE *fopen(const char * nomeDoArquivo,
    const char * modo);
----

A função `fopen` retorna um ponteiro para `FILE` se conseguir abrir o
arquivo, caso contrário retorna `NULL`.

nomeDoArquvo:: nome do arquivo que será aberto

mode::
Modo de abertura do arquivo.
`r`::: abre arquivo de texto para leitura
`w`::: abre arquivo de texto para escrita
`wx`::: cria arquivo de texto para escrita
`a`::: adiciona ao final; o indicador de posição de arquivo é
posicionado no final do arquivo
`rb`::: abre arquivo binário para leitura
`wb`::: abre arquivo binário para escrita
`ab`::: abre arquivo binário para escrita, no final do arquivo

[id="fclose", reftext="fclose()"]
==== fclose()

(((fclose)))

[source,c]
----
int fclose(FILE *arquivo);
----

Uma chamada realizada com sucesso invoca o <<fflush>> e fecha o arquivo.

A função retorna zero caso o string foi fechado com sucesso, ou `EOF`
caso houve erro no fechamento.

[id="fgetc", reftext="fgetc()"]
==== fgetc()

(((fgetc)))

[source,c]
----
int fgetc(FILE *arquivo);
----

Ler um carácter do arquivo.

Caso em caso de erro ou não houver mais carácteres, retorna `EOF`.

[id="getchar", reftext="getchar()"]
==== getchar()

(((getchar)))

[source,c]
----
#include <stdio.h>
int getchar(void);
----

Ler um carácter da entrada padrão, equivale a `fgetc(stdin)`:

Ver <<fgetc>>.

[id="fputc", reftext="fputc()"]
==== fputc()

(((fputc)))

[source,c]
----
#include <stdio.h>
int fputc(int caracter, FILE *arquivo);
----

Escreve um carácter no arquivo.

Retorna o carácter escrito. Se houve erro, o indicador de erro é
setado e retorna `EOF`.



[id="putchar", reftext="putchar()"]
==== putchar()

(((putchar)))

[source,c]
----
#include <stdio.h>
int putchar(int caracter);
----

Escreve um carácter na saída padrão.

Retorna o carácter escrito. Se houve erro, o indicador de erro é
setado e retorna `EOF`.

- Ver <<fputc>>.

[id="fgets", reftext="fgets()"]
==== fgets

(((fgets)))

[source,c]
----
#include <stdio.h>
char *fgets(char * string, int n, FILE * arquivo);
----

Ler um string de `arquivo` e salva o conteúdo em `string`.

Retorna `string` se realizado com sucesso. Se o final do arquivo foi
encontrado e não leu nenhum carácter então `string` não é alterado e
`NULL` é retornado. Se ocorreu algum erro o valor de `string` é
indeterminado e retorna `NULL`.

////
The fgets function returns s if successful. If end-of-file is encountered and no
characters have been read into the array, the contents of the array remain unchanged and a
null pointer is returned. If a read error occurs during the operation, the array contents are
indeterminate and a null pointer is returned.
////

[id="fputs", reftext="fputs()"]
==== fputs

(((fputs)))

[source,c]
----
#include <stdio.h>
int fputs(const char * string, FILE * arquivo);
----

////
The fputs function writes the string pointed to by s to the stream pointed to by
stream. The terminating null character is not written.

The fputs function returns EOF if a write error occurs; otherwise it returns a
nonnegative value.
////

Escreve `string` na posição atual de `arquivo`. O carácter nulo de
término não é escrito.

Retorna `EOF` se houve erro na escrita; caso contrário retorna um
valor maior ou igual a zero.

Ver <<fgets>>.

[id="fread", reftext="fread()"]
==== fread()

(((fread)))

[source,c]
----
#include <stdio.h>
size_t fread(void * ponteiro, size_t tamanho, size_t
    quantidade, FILE * arquivo);
----

////
The fread function reads, into the array pointed to by ptr, up to nmemb elements
whose size is specified by size, from the stream pointed to by stream. For each
object, size calls are made to the fgetc function and the results stored, in the order
read, in an array of unsigned char exactly overlaying the object. The file position
indicator for the stream (if defined) is advanced by the number of characters successfully
read. If an error occurs, the resulting value of the file position indicator for the stream is
indeterminate. If a partial element is read, its value is indeterminate.

The fread function returns the number of elements successfully read, which may be
less than nmemb if a read error or end-of-file is encountered. If size or nmemb is zero,
fread returns zero and the contents of the array and the state of the stream remain
unchanged.
////

A função ler para o buffer `ponteiro` até quantidade `quantidade` de elementos,
de tamanho `tamanho` do arquivo `arquivo`. O indicador de posição é
avançado de acordo com a quantidade de carácteres lidos.

A função retorna o número de elementos lidos, que pode ser menor do
que `quantidade` caso encontrou o final do arquivo ou houve erro. Se
`quantidade` ou `tamanho` for zero, o conteúdo de `ponteiro` não é
alterado.

[id="fwrite", reftext="fwrite()"]
==== fwrite()

(((fwrite)))

[source,c]
----
#include <stdio.h>
size_t fwrite(const void * ponteiro, size_t tamanho, size_t
    quantidade, FILE * arquivo);
----

////
The fwrite function writes, from the array pointed to by ptr, up to nmemb elements
whose size is specified by size, to the stream pointed to by stream. For each object,
size calls are made to the fputc function, taking the values (in order) from an array of
unsigned char exactly overlaying the object. The file position indicator for the
stream (if defined) is advanced by the number of characters successfully written. If an
error occurs, the resulting value of the file position indicator for the stream is
indeterminate.

The fwrite function returns the number of elements successfully written, which will be
less than nmemb only if a write error is encountered. If size or nmemb is zero,
fwrite returns zero and the state of the stream remains unchanged.
////

A função escreve na posição apontada por `ponteiro`, até a quantidade
`quantidade` de elementos do tamanho `tamanho` no arquivo `arquivo`.
O indicador de posição é incrementado de acordo com a quantidade de
bytes escritos.

A função retorna o número de elementos escritos, que pode ser menor do
que `quantidade` caso houve erro. Se `quantidade` ou `tamanho` for
zero, nada é escrito no arquivo.

[id="fflush", reftext="fflush()"]
==== fflush()

(((fflush)))

[source,c]
----
#include <stdio.h>
int fflush(FILE *arquivo);
----

////
If stream points to an output stream or an update stream in which the
most recent operation was not input, the fflush function causes any
unwritten data for that stream to be delivered to the host environment
to be written to the file; otherwise, the behavior is undefined.

If stream is a null pointer, the fflush function performs this
flushing action on all streams for which the behavior is defined
above.

The fflush function sets the error indicator for the stream and
returns EOF if a write error occurs, otherwise it returns zero.
////

Causa a escrita de qualquer dado que ainda não foi escrito no arquivo.

Retorna `EOF` se houve erro na escrita ou zero se a escrita foi
realizada com sucesso.

[id="fseek", reftext="fseek()"]
==== fseek()

(((fseek)))

Move o indicador de posição do arquivo.

[source,c]
----
#include <stdio.h>
int fseek(FILE *arquivo, long int deslocamento, int whence);
----

Ver http://www.cplusplus.com/reference/cstdio/fseek/.

[id="ftell", reftext="ftell()"]
==== ftell()

(((ftell)))

Retorna a posição atual no arquivo.

[source,c]
----
#include <stdio.h>
long int ftell(FILE *arquivo);
----

Ver http://www.cplusplus.com/reference/cstdio/ftell/, <<fseek>>.

[[rewind]]
[id="rewind", reftext="rewind()"]
==== rewind()

(((rewind)))

[source,c]
----
#include <stdio.h>
void rewind(FILE *stream);
----

Retroce o indicador de posição para o início do arquivo. É equivalente
a:

[source,c]
----
(void)fseek(arquivo, 0L, SEEK_SET)
----

[id="fscanf", reftext="fscanf()"]
==== fscanf()

(((fscanf)))

[source,c]
----
#include <stdio.h>
int fscanf(FILE * arquivo, 
  const char * formato, ...);
----

// TODO fscanf

[id="scanf", reftext="scanf()"]
==== scanf()

(((scanf)))

Ver <<fscanf>>.


[id="printf", reftext="printf()"]
==== printf()

(((printf)))

Ver <<fprintf>>.

[id="fprintf", reftext="fprintf()"]
==== fprintf

(((fprintf)))

[source,c]
----
#include <stdio.h>
int fprintf(FILE * arquivo, 
    const char * formato, ...);
----

===== Flags

`-`::
O resultado é justificado a esquerda, se não for especificado é justificado a direita.

`+`::
O resultado da conversão sempre será prefixado com o sinal do número (positivo ou negativo).

_espaço_::
Se o resultado for prefixado com _espaço_ então ele será impresso.

`0`::
Imprime zeros a esquerda do número.

`#`::
O Resultado é apresentado utilizando um _formato alternativo_.


===== Modifidores de tamanho

Os modificadores de tamanho especficam qual o tamanho será
utilizado na conversão. O tamanho independete do sinal 
(`signed` ou `unsigned`).

[width="60%",cols="^m,^m",frame="topbot",options="header"]
|====
| Modificador | Tamando do tipo
| hh | char 
| h  | short
| l  | long
| ll | long long
| L  | long double
|====

===== Especificaadores de Conversão de tipos

`d,i` (tipo decimal com sinal)::
O argumento int é convertivo para um decimal com sinal no estilo
[-]dddd.  A precisão especifica o número mínimo de dígitos a aparecer;
se o valor convertido pode ser representado com menos dígitos, ele é
expandido com zeros.  A precisão padrão é 1. O resultado da conversão
de Zero com a precisão de Zero é nenhum carácter.

`u,o,x,X` (tipo decimal sem sinal, octal, ou hexadecimal)::
O argumento unsigned int é convertido para unsigned octal *(o)*,
unsigned decimal *(u)*, ou notação unsigned hexadecimal (*x* or *X*)
no estilo dddd; as letras abcdef (de hexadecimal) são usadas na
conversão com _x_ e ABCDEF para conversão com _X_. A precisão
especifica o número mínimo de dígitos a aparecer; se o valor a ser
convertido pode ser representado com menos dígitos, ele é expandido
com zeros a esquerda. A precisão padrão é 1. O resultado da conversão
de Zero com a precisão de Zero é nenhum carácter.

`f,F` (tipo double)::
O argumento double representando o número de ponto flutuante é
convertido para a notação decimal no estilo [-]ddd.ddd, em que o
número de dígitos depois do carácter ponto é igual a especificação da
precisão. Se a precisão não for especificada, é assumido 6; se a
precisão for zero e a flag `#` não for utilizada, o ponto não irá
aparecer. Se o ponto foi espeficado então pelo menos um dígito é
impresso antes dele. O valor é arredondado para o número de dígitos
apropriados.

`c` (tipo carácter)::
O argumento inteiro é convertido para `unsigned char`, e o carácter
resultante é escrito.

`s` (tipo string)::
O argumento deve um ponteiro para o início de um array de `char`. Os
carácteres do array serão impressos até encontrar o carácter null `\0`
(que não será impresso).

`%`::
O carácter `%` é escrito. A especificação completa deve ser ``%%''.

===== Resumo e utilização do formato

A <<fig_printf>> resume o formato utilizado nas funções
<<fprintf>> e <<printf>>. 

NOTE: Na plataforma em que esta figura foi
criada os tipos `long int` e `int` possuem o mesmo tamanho.

[[fig_printf]]
.Resumo do formato de fprintf e printf
image::images/bibliotecas/fprintf-formato.pdf[scaledwidth="100%"]

[[ex_formato_printf]]
.Exemplo de utilizações do formato de `printf`
====
.Código fonte
{online}/aprendendo_printf.c[{local}/aprendendo_printf.c]

[source, c]
----
include::{local}/aprendendo_printf.c[]
----

.Saída da execução
....
include::{local}/aprendendo_printf.out[]
....

====



////
Difference between format specifiers %i and %d in printf?

These are identical for printf but different for scanf. For printf,
both %d and %i designate a signed decimal integer. For scanf, %d and
%i also means a signed integer but %i inteprets the input as a
hexadecimal number if preceded by 0x and octal if preceded by 0 and
otherwise interprets the input as decimal.
////

[id="feof", reftext="feof()"]
==== feof

(((feof)))

[source,c]
----
#include <stdio.h>
int feof(FILE *arquivo);
----

////
The feof function tests the end-of-file indicator for the stream pointed to by stream.

The feof function returns nonzero if and only if the end-of-file indicator is set for
stream.
////

Testa se o indicador do final de arquivo de `arquivo`.

Retorna um valor não zero se o indicador de final de arquivo foi setado em `arquivo`.



[id="math_h",reftext="math.h"]
=== math.h

(((math.h)))

Funções matemáticas.


[id="M_PI",reftext="M_PI"]
==== M_PI

[source,c]
----
#include <math.h>
#define M_PI 3.14159265358979323846
----

`M_PI` é uma macro que contém uma definição de π.


[id="fabs",reftext="fabs()"]
==== fabs()

(((fabs)))

[source,c]
----
#include <math.h>
double fabs(double x);
float fabsf(float x);
long double fabsl(long double x);
----

Calcula módulo ou valor absoluto de x: `|x|`.

[id="pow",reftext="pow()"]
==== pow()

(((pow))) (((potência)))

[source,c]
----
#include <math.h>
double pow(double x, double y);
float powf(float x, float y);
long double powl(long double x, long double y);
----

Retorna x elevado a y: x^y^.

[id="sqrt",reftext="sqrt()"]
==== sqrt()

(((sqrt))) (((raiz quadrada)))

[source,c]
----
#include <math.h>
double sqrt(double x);
float sqrtf(float x);
long double sqrtl(long double x);
----

Calcula a raiz quadrada de x: x:[\sqrt{x}].


////
Terminando arquivo com linha em branco
////

