[appendix]
== Bibliotecas

:online: {gitrepo}/blob/master/livro/capitulos/code/biblioteca
:local: code/biblioteca

[[c1x]]
=== Padrão C1X da Linguagem C

O último padrão adotado para a Linguagem C foi publicado pela ISO em
12/8/2011 no documento: ISO/IEC 9899:2011. Este padrão é conhecido
como C11 ou C1X, você pode consultar gratuitamente a última versão
pública do documento em:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf.

NOTE: Durante o livro iremos referenciar este documento apenas por
``Padrão C1X''.

IMPORTANT: Nas seções a seguir nós resumimos a documentação das
funções e bibliotecas utilizadas neste livro. No entanto, nós
recomendamos a consulta da documentação original (em inglês).


[id="sec_main",reftext="main()"]
=== main()
TODO: Explicar os parâmetros da função `main`.

[id="assert_h",reftext="assert.h"]
=== assert.h

TIP: Mais informações sobre esta função pode ser consultada na seção
``7.2 Diagnostics <assert.h>'' no padrão C1X da linguagem C. Os
seguintes sites também podem ajudá-lo a compreender esta função:
http://www.acm.uiuc.edu/webmonkeys/book/c_guide/2.1.html,
http://pt.wikipedia.org/wiki/Assert.h e
http://www.cplusplus.com/reference/cassert/assert/.



[id="assert", reftext="assert()"]
==== assert()

 void assert ( int expressao )

Esta função costuma ser utilizado

[[TIP]]
====
Ajuda online:
http://www.cplusplus.com/reference/cassert/assert/

====

[id="stdlib_h",reftext="stdlib.h"]
=== stdlib.h

==== EXIT_SUCCESS
Constante para indicar que não houve erro.

==== EXIT_FAILURE
Constante para indicar que houve erro na execução do arquivo.


[[f_exit]]
==== exit()

  void exit( int codigoDeErro )

Termina o programa indicando o código de erro.

==== Gerência de memória

[[malloc]]
===== malloc
TODO

[[calloc]]
===== calloc

A função `calloc`, além de alocar espaço na memória, inicializa todo o
espaço alocado com `0` (zeros). 

----
void *calloc(size_t quantidade, size_t tamanho);
----

[[free]]
===== free
TODO


[id="string_h", reftext="string.h"]
=== string.h

TODO: funçõe de string.

[id="strlen", reftext="strlen()"]
====  strlen()
Retorna tamanho do string, até encontrar o carácter `\0`.

[id="strcmp", reftext="strcmp()"]
==== strcmp()
Compara dois strings.

[id="strncmp", reftext="strncmp()"]
==== strncmp()
Compara dois strings até uma posição específica.


[id="strcpy", reftext="strcpy()"]
==== strcpy

----
char *strncpy(char * restrict destino, 
    const char * restrict origem, size_t quantidade);
----

[id="stdbool_h", reftext="stdbool.h"]
=== stdbool.h

TODO: atualizar.

Inclusão da biblioteca <<stdbool_h>>, que define o tipo `bool`. Este
tipo pode ser utilizado como retorno de expressões lógicas. Além disso
também estão definidos macro `true` com o valor `1` e `false` com o
valor `0`.

[id="stdio_h", reftext="stdio.h"]
=== stdio.h

NOTE: A documentação sobre as funções de leitura de arquivo estão contidas
na seção ``7.21 Input/output <stdio.h>'' do padrão C1X.

[id="fopen", reftext="fopen()"]
==== fopen()
A função `fopen` retorna um ponteiro para `FILE` se conseguir abrir o
arquivo, caso contrário retorna `NULL`.

----
#include <stdio.h>
FILE *fopen(const char * restrict nomeDoArquivo,
    const char * restrict modo);
----

nomeDoArquvo:: nome do arquivo que será aberto

mode::
Modo de abertura do arquivo.
r::: abre arquivo de texto para leitura
w::: abre arquivo de texto para escrita
wx::: cria arquivo de texto para escrita
a::: adiciona ao final; o indicador de posição de arquivo é
posicionado no final do arquivo
rb::: abre arquivo binário para leitura
wb::: abre arquivo binário para escrita
ab::: abre arquivo binário para escrita, no final do arquivo



[id="fclose", reftext="fclose()"]
==== fclose()
TODO

[id="fgetc", reftext="fgetc()"]
==== fgetc()
TODO

[id="getchar", reftext="getchar()"]
==== getchar()
Ver <<fgetc>>.

[id="fputc", reftext="fputc()"]
==== fputc()
TODO

[id="putchar", reftext="putchar()"]
==== putchar()
Ver <<fputc>>.

[id="fgets", reftext="fgets()"]
==== fgets
TODO.

[id="fputs", reftext="fputs()"]
==== fputs
TODO.
Ver <<fgets>>.

[id="fread", reftext="fread()"]
==== fread()
TODO

[id="fwrite", reftext="fwrite()"]
==== fwrite()
TODO

[id="fseek", reftext="fseek()"]
==== fseek()
TODO.

[id="ftell", reftext="ftell()"]
==== ftell()
TODO.

[id="printf", reftext="printf()"]
==== printf()
Ver <<fprintf>>.

[id="fprintf", reftext="fprintf()"]
==== fprintf
TODO.

[[frewind]]
[id="frewind", reftext="frewind()"]
==== frewind
TODO.


[id="feof", reftext="feof()"]
==== feof
TODO.


////
Terminando arquivo com linha em branco
////

