== Ponteiros

:online: {gitrepo}/blob/master/livro/capitulos/code/cap3
:local: code/cap3

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* Entender o conceito de ponteiros e utilizá-los em funções, vetores, 
registros ou estruturas, dentre outras;
* Aprofundar o conhecimento sobre armazenamento e manipulação de dados no 
computador;
____

No início do capitulo anterior, foi discutido que o conhecimento de linguagens 
de programação específicas, por si só, não habilita ou não é suficiente 
para programadores, é imprescindível saber usá-las de maneira eficiente. Foi 
visto também que o projeto de um algoritmo ou programa engloba, entre outras, 
a fase da modelagem computacional de um problema, a qual por sua vez possui uma 
etapa de identificação das propriedades dos dados (ou informações contidas 
no problema) e suas características funcionais. Dessa forma, uma 
representação adequada dos dados ou informações do problema, em vista das 
funcionalidades que devem ser atendidas, constitui uma etapa fundamental para a 
obtenção de programas eficientes.

Neste capítulo serão abordados os conceitos de ponteiros e a sua aplicação 
para alocação dinâmica de memória. Será visto o uso de ponteiros em 
funções ou sub-rotinas, vetores, registros ou estruturas, vetores de 
registros, dentre outros.

=== Armazenamento de dados no computador

Para armazenar dados no computador um programa gerencia fundamentalmente três 
parâmetros, a saber, onde a informação está armazenada, que tipo de 
informação é armazenada e que valor é mantido lá. O primeiro refere-se ao 
endereço de memória onde os dados são gravados. O segundo refere-se ao tipo 
de dado, ou seja, qual o tipo de estrutura (variável, array, registros, dentre 
outras) e qual a natureza da informação armazenada (real, inteiro, 
caracteres, número sem sinal, dentre outras), essas informações são 
importantes para se calcular o espaço de memória que será necessário para o 
armazenamento desses dados. O último parâmetro refere-se aos valores que são 
atribuídos pelo usuário ou calculados no próprio programa e que serão 
armazenados nas estruturas de dados. O exemplo mais simples para ilustrar o que 
foi colocado, é o processo de declaração de uma variável num programa. 

Como ilustrado na <<fig_uso_memoria_por_variavel>>, nesse caso, são realizados basicamente dois 
passos, a declaração da variável em si e a atribuição de um valor a essa 
variável. Note na <<fig_uso_memoria_por_variavel>> que no momento em que a variável `soma` é 
declarada, é alocado na memória RAM do computador um espaço de memória para 
a essa variável (posições `0xCB22` e `0xCB23`). Esse espaço de memória é 
preenchido quando um valor é atribuído a variável, como por exemplo, o valor 3126.

// FIXME: dois bytes não equivale a uma short?

[[fig_uso_memoria_por_variavel]]
.Ilustração de uso da memória por uma variável em um programa em C.
image::images/cap3/declaracao-atribuicao-memoria.eps[scaledwidth="70%"]

Um cuidado importante que todo programador deve ter é inicializar as 
variáveis antes do seu uso. Veja no código a seguir que, quando não se 
inicializa uma variável, o valor que ela assume é aleatório e depende do 
``lixo'' no espaço de memória onde foi criada. No momento em que esse 
código foi criado, compilado e executado o valor de `conta` foi 624.756.000,00! 
Ou seja, um valor totalmente aleatório e que muda a cada vez que a memória 
RAM do computador é inicializada. Você iria trabalhar a vida inteira para 
pagar essa conta de luz! O correto é inicializar a variável antes de 
utilizá-la. Como exercício, compile e execute o código a seguir com e sem o 
comentário indicado. Certamente, com a linha comentada, o valor impresso 
na tela será diferente em cada computador em que esse código for executado.

.Código fonte
{online}/variavel_nao_inicializada.c[{local}/variavel_nao_inicializada.c]

[[variavel_nao_inicializada]]
[source, c]
.Programa para demonstrar valor de variável não inicializada
----
include::{local}/variavel_nao_inicializada.c[]
----


Dessa forma, todo nome de variável está associado a um endereço na memória. 
O *((operador de endereço))* `&` pode ser usado para obter a localização de uma 
variável na memória, ou seja, o endereço de memória. O código a seguir 
mostra como esse operador pode ser utilizado para se obter o endereço de 
memória onde uma variável foi criada. Note que no `printf`, o `%p` foi utilizado 
como formato para endereço de memória.

.Código fonte
{online}/operador_de_endereco.c[{local}/operador_de_endereco.c]

[source, c]
.Programa para demonstrar uso do Operador de Endereço
----
include::{local}/operador_de_endereco.c[]
----

.Saída da execução do programa
....
include::{local}/operador_de_endereco.data[]
....


[[sec_ponteiros_definicao]]
=== Definição de ponteiros

(((Ponteiro)))

Outra estratégia para armazenar e manipular dados no computador é: 

* Alocar memória manualmente;

* Guardar o endereço de memória em um ponteiro;

* Usar o ponteiro para acessar e modificar os dados.

Ou seja, é necessário definir e utilizar ponteiros no programa. Um ponteiro 
é um tipo especial (``variável especial'') que guarda valores que são 
endereços de memória. Em outras palavras, um ponteiro é uma variável que é 
utilizada para se armazenar endereços de memória. Em geral, um ponteiro é 
associado a uma variável, ou seja, o ponteiro contém um endereço de uma 
variável que contém um valor específico. A referência de um valor por meio 
de um ponteiro é chamada de (((Ponteiro, indireção))) *indireção*.

A declaração de um ponteiro segue o seguinte padrão:

 float *ptr; // Lê-se "ptr é um ponteiro para um float"

Em que `float` especifica o tipo de elemento apontado pelo ponteiro, `ptr` é o 
nome que está sendo dado ao ponteiro, `*` é o *((operador de indireção))* e é 
usado para se definir um ponteiro. 

Como o ponteiro contém um endereço de memória, diz-se que ele aponta para 
aquela posição de memória. A <<fig_memoria_declaracao_inicializacao>> ilustra a 
definição de um ponteiro com nome `ptr`, que é utilizado para apontar para a 
variável `float soma`. Note que na linha 4 `ptr` é declarado. Até esse momento não existe nenhuma 
relação entre o ponteiro `ptr` e a variável `soma`. No final, `ptr` é associado 
a variável `soma` por meio do comando `ptr = &soma`, ou seja, `prt` recebe o 
endereço de memória da variável `soma` usando o *((operador de endereço))* `&`. A 
partir desse comando, o programador pode utilizar o ponteiro `ptr` para manipular 
o conteúdo armazenado na variável `soma`. A seguir será visto como isso é feito.

[[fig_memoria_declaracao_inicializacao]]
.Ilustração de declaração e inicialização de um ponteiro na memória
image::images/cap3/memoria-declaracao-e-inicializacao-ponteiro.eps[scaledwidth="70%"]

O nome de um ponteiro representa uma localização na memória. Outra função 
do *((operador de indireção))* `*` é ser usado para se obter o valor armazenado na 
memória. Ou seja, é a partir do operador `*` que o programador pode manipular o 
conteúdo da variável para qual o ponteiro está apontando.

IMPORTANT: Sempre inicialize um ponteiro que você declarou em um programa. Um 
ponteiro só terá utilidade em um programa quando for inicializado, ou seja, 
for associado a algum elemento.

Um ponteiro pode ser inicializado com `NULL`, 0 (zero) ou um endereço de uma 
variável usando o operador de endereço ``&''. Um ponteiro com valor `NULL` não 
aponta para nada. `NULL` é uma constante simbólica definida na biblioteca 
`<stddef.h>` e também em `<stdio.h>`. A inicialização do ponteiro com o valor `0` 
(zero) é equivalente a inicializar com `NULL`, todavia em geral usa-se a 
inicialização com `NULL`.

NOTE: Outras linguagens de programação utilizam `nil`, ou `null` com o mesmo significado.

Outra maneira de se inicializar ponteiros é associando-o diretamente a uma variável. Para isso o ((operador de endereço)) ``&'' deve ser utilizado.  A <<fig_inicializacao_ponteiro>>(a) ilustra que, ao declarar um ponteiro, o computador não aloca automaticamente 
memória para guardar o valor apontado e, nesse caso, o comando `*pt = 230.8` 
não faz sentido. É preciso inicializar o ponteiro como mostrado na <<fig_inicializacao_ponteiro>>(b), 
ou seja, o ponteiro `pt` é declarado e associado a variável `N1`. Em seguida, 
pode-se utilizar o ponteiro para armazenar o valor 230.8 na variável `N1`. 

[[fig_inicializacao_ponteiro]]
.Utilização de ponteiro. 
image::images/cap3/inicializacao-ponteiro.eps[scaledwidth="70%"]

WARNING: Na <<fig_inicializacao_ponteiro>>(a) é demonstrada uma forma
errada da utilização de ponteiro, ao atribuir um valor a um ponteiro
não inicializado. Em b) é apresentada a forma correta, com atribuição
de valor após ponteiro inicializado.  

[NOTE]
====
Na declaração de um ponteiro o uso de espaços ao redor do * é opcional.

 int *pt;  // enfatiza que *pt é um int
 int* pt;  // enfatiza que pt é um ponteiro para int 
 int * pt; // estilo neutro
====

[CAUTION]
====
Cuidado com declarações múltiplas.

 char *p1, p2;  // p1 é um ponteiro para char, 
                // p2 é uma variável do tipo char

 char *p1, *p2;  // p1 e p2 são ponteiros para char
====

Com o intuito de sedimentar o conceito de ponteiros, o código a seguir mostra 
um exemplo de como um ponteiro é usado para manipular o conteúdo da variável 
para qual está apontando.  Execute esse programa no seu computador e
faça modificações à vontade para você melhor absorver o conceito de ponteiros.

.Código fonte
{online}/usando_ponteiro.c[{local}/usando_ponteiro.c]

[source, c]
.Usado ponteiro para alterar variável
----
include::{local}/usando_ponteiro.c[]
----

<1> o ponteiro `pt` é criado
<2> `pt` é inicializado com o endereço de `total`
<3> Impressão do *valor* de `total` e seu *endereço*
<4> Impressão do *endereço* apontado por `pt`
<5> Impressão do *valor* endereçado por `pt`
<6> ((operador de indireção)) `*` é utilizado para alterar o valor da
    variável `total` por meio do ((ponteiro)) 
<7> Impressão do *valor* da variável `total`, que teve seu valor alterado
    pela utilização de ponteiro.

.Resultado da execução
....
include::{local}/usando_ponteiro.out[]
....

Finalmente, recapitulando, note que há dois operadores que são utilizados 
para a manipulação e/ou definição de ponteiros, a saber, o operador `&`, 
conhecido como *((operador de endereço))*, e o operador `*`,
normalmente chamado de *((operador de indireção))*. 

O operador de endereço:: é utilizado para se obter o endereço de seu
operando ou variável a que é aplicado. 

O operador de indireção:: pode ser utilizado de duas formas, a
primeira para definição de um ponteiro; já a segunda função é retornar
o valor ou conteúdo da variável para a qual um ponteiro está
apontando.


[[sec_ponteiros_funcao]]
=== Ponteiros em funções ou sub-rotinas

==== Contextualização

Para entendermos a utilidade do uso de ponteiros em funções é preciso antes 
analisar aspectos da execução de uma função em um programa em C, como,
por exemplo, a *((pilha de execução))* de uma *((função))* e
transferência de dados para o programa principal (função `main`).

As funções em um programa em C são independentes entre si. Como 
consequência, as *((variáveis locais))* definidas dentro do 
*((escopo de uma função))*, inclusive os parâmetros de entrada da função, não
existem fora dela. Isso significa que cada vez que uma função é
executada, as suas variáveis locais são criadas, e após a sua
execução, essas variáveis locais deixam de existir. 

Outra característica básica no conceito de funções é que a transferência de
dados entre funções é feita com o uso de parâmetros e do valor de
retorno da função chamada. Ou seja, uma função pode retornar um valor
para a função que a chamou por meio do comando `return`.

Para entendermos melhor a transferência de dados entre funções e o fluxo de 
dados dentre do escopo de uma função, um exemplo detalhado é dado e sua 
execução é analisada usando o esquema ilustrado na <<fig_pilha_de_execucao>>. 
Essa figura esboça o conceito de *((pilha de execução))* na memória RAM do computador, na 
qual os nomes das variáveis e/ou das funções são mostrados à direita de 
cada célula/linha, o valor/conteúdo que uma variável assume no momento da 
execução da função é mostrado em cada célula/linha da coluna e, 
finalmente, o endereço de memória onde cada variável está gravada é 
mostrado à esquerda de cada célula/linha. 

[[fig_pilha_de_execucao]]
.Ilustração da pilha de execução na memória RAM do computador.
image::images/cap3/pilha_de_execucao.eps[scaledwidth="50%"]

// FIXME: Atualizar imagem de pilha de execução #17


Considere agora o código mostrado a seguir. Esse exemplo mostra um programa 
que calcula a soma dos números pares entre 0 e 200. A etapa de cálculo da 
soma é feita na função `f_soma`, a qual é chamada na linha 11 dentro da 
_função principal_ (função `main` ou função chamadora). Como dito 
anteriormente, quando uma função é executada, as suas _((variáveis locais))_ são 
criadas, e após a sua execução, essas variáveis locais deixam de existir. 
Note no código exemplo que, após a execução da função `f_soma`, a variável 
`PAR` dentro da função `f_soma` terá valor 0 (zero). Ou seja, diferente do valor 
200 que `PAR` possui após a execução da função `main`, já que seu valor não 
foi alterado dentro da função principal. O que acontece é que `PAR` 
(parâmetro da função `f_soma`) é uma _((variável local))_ inicializada com o valor 
passado na chamada da função. Sendo assim, `PAR` dentro da função `f_soma` não 
representa a `PAR` dentro da função main; o fato delas terem o mesmo nome é 
indiferente.

.Código fonte
{online}/f_soma.c[{local}/f_soma.c]

[source, c]
----
include::{local}/f_soma.c[]
----


[TIP]
Como exercício para casa e para visualizar o que foi dito, inclua, usando o 
comando `printf`, a impressão da variável `PAR` dentro da função `main` e após o 
`while` dentro da função `f_soma`. Veja que dentro da função `main` será 
impresso o valor 200 e após o `while` da função `f_soma` será impresso o valor 
0 (zero).

// TODO fornecer link com resolução ou adicionar a exercícios resolvidos?

Continuando o debate, será mostrada agora a _((pilha de execução))_ na
memória do programa em questão. Será utilizada a notação descrita na
Fig. 3.4.  Resumidamente, a pilha de execução funciona da seguinte
forma. Cada variável local de uma função de uma função é colocada na
pilha de execução. As chamar uma função, os parâmetros da função são
copiados para a pilha e tratados como se fossem variáveis locais da
função chamada. Quando a execução da função é concluída, a parte da
pilha correspondente àquela função é liberada. Por isso, não se pode
acessar as variáveis locais de fora da função em que foram definidas.
Perceba na <<fig_pilha_executando>>(a) que quando o programa inicia, a
função `main` inicia com a pilha vazia. Seguindo na execução do
programa (linhas 7 a 10 do programa), a <<fig_pilha_executando>>(b)
mostra a definição e inicialização das variáveis `soma` e `PAR` na
pilha. Com a chamada da função (linha 11), a
<<fig_pilha_executando>>(c) apresenta a variável `PAR` da função
`f_soma` na pilha de execução (observe que `PAR` inicia com valor
200). A  <<fig_pilha_executando>>(d) ilustra a criação/inicialização
da variável local `s` dentro da função `f_soma`. A
<<fig_pilha_executando>>(e) mostra a situação da pilha após o laço
`while` (linha 22), note que agora `PAR` possui valor 0 (zero) e `s`
10100.0 (que é a soma dos números pares entre 0 e 200). Nesse caso,
veja que a variável `PAR` dentro da função `main` continua com seu
valor inicial, ou seja, 200. A  <<fig_pilha_executando>>(f) mostra a
situação após o retorno da função (linha 23), ou seja, o valor
retornado pela função `f_soma` é armazenado na variável soma dentro da
função `main` (linha 11).

[[fig_pilha_executando]]
.Ilustração da pilha de execução na memória RAM de um programa em execução.
image::images/cap3/pilha_de_execucao_em_execucao.eps[scaledwidth="80%"]

[[sec_ponteiros_passagem_parametro]]
==== Passagem de parâmetros em funções: passagem por valor vs passagem por referência

Na subseção anterior foi vista a pilha de execução de um programa com 
funções em C e concluiu-se que não se pode modificar valores das variáveis 
locais pertencentes a uma função fora do escopo de tal função. Esse tipo de 
passagem de parâmetros que foi vista anteriormente é chamada *((passagem por valor))*. 
Nesse caso, uma _cópia_ dos parâmetros da função é feita e passada 
para a função chamada e, portanto, as mudanças nessa _cópia_ não afetam o 
valor original da variável chamadora. 

[IMPORTANT]
====
Todas as chamadas em C são feitas por valor. Cabe ao programador 
identificar as situações em que se deseja empregar a passagem por referência.

A chamada por valor deverá ser usada sempre que não se desejar/precisar 
modificar o valor da variável original que foi chamada.

====

Todavia, muitas funções exigem a necessidade de modificar uma ou mais 
variáveis na função chamadora ou passar um ponteiro para um objeto com 
grande quantidade de dados (por exemplo, um array), para evitar a sobrecarga de 
passar o objeto inteiro por valor, ou seja, isso implicaria na sobrecarga de 
ter de fazer uma cópia do objeto inteiro na pilha de execução. Uma outra 
limitação do uso de *((passagem por parâmetro))* é que nesse tipo de 
implementação a função só pode retornar *um único valor* para a função 
chamadora. Quando se deseja retornar mais de um valor, o esquema de passagem 
por valor não poder ser utilizado. Para resolver esses problemas, usa-se em 
Cfootnote:[Outras linguagens com Lua e Ruby permitem funções retornar 
vários valores, que podem ser atribuídos a mais de uma variável.]
a passagem de (((parâmetros por referência))) *parâmetros por
referência* para as funções e é necessário o uso de ponteiros para
esse fim. 


Para melhor entender esse debate, a seguir é dado um exemplo simples de um 
programa para se calcular a soma e subtração de dois números inteiros. Vamos 
iniciar com um programa que usa uma função para calcular a subtração de 
dois números inteiros:

.Código fonte
{online}/subtracao-passagem-por-valor.c[{local}/subtracao-passagem-por-valor.c]

[source, c]
----
include::{local}/subtracao-passagem-por-valor.c[]
----

<1> Salvando na variável `sub` o retorno da função `calculadora`.

(((passagem de parâmetros por valor)))

Nesse exemplo não há um problema explícito, pois o resultado da subtração 
é retornado pela função `calculadora` explicitamente e armazenado 
na variável `sub`. Um dos problemas da *passagem de parâmetros por 
valor* acontece quando se deseja retornar em uma função mais de um valor para 
a função `chamadora`. Vamos supor que agora se deseje retornar o valor da soma 
e subtração de dois números inteiros. Usando a ideia da passagem de 
parâmetros por valor uma forma incorreta de se implementar esse programa é 
mostrada a seguir.

.Código fonte
{online}/passagem_incorreta.c[{local}/passagem_incorreta.c]

[source, c]
.Titulo do código
----
include::{local}/passagem_incorreta.c[]
----

.Execução da aplicação
....
include::{local}/passagem_incorreta.out[]
....

Como se sabe e já foi alertado no texto, esse código não funciona. Serão 
impressos na tela valores incorretos e que dependem da execução em cada 
computador, os valores das variáveis `sub` e `soma` calculados na função 
`calculadora` não possuem relação com as variáveis `sub` e `soma` impressos na 
função chamadora (nesse caso a função `main`) na linha 10. 

(((passagem de valores por referência)))

Para resolver esse problema é preciso usar a *passagem de valores por 
referência*, ou seja, passar ponteiros para a função. Como já se sabe, com o 
uso de ((ponteiros)) é possível alterar indiretamente valores de variáveis. 
Dessa forma, se for passado para uma função os valores dos endereços de 
memória em que suas variáveis estão armazenadas (i.e., os ponteiros que 
apontam para essas variáveis), essa função pode alterar _indiretamente_ os 
valores das variáveis na função chamadora. Usando-se essa estratégia, é 
possível resolver o problema do último exemplo. Isso é feito no código a 
seguir.

.Código fonte
{online}/passagem_por_referencia.c[{local}/passagem_por_referencia.c]

[source, c]
----
include::{local}/passagem_por_referencia.c[]
----
<1> Protótipo da função cabeçalho definindo receber ponteiros como
    parâmetros.
<2> Chamada da função calculadora, similar ao programa anterior, mas
    agora passa o endereço das variáveis.
<3> Implementação da função com os ponteiros, similar ao cabeçalho.
<4> Atualização das variáveis utilizando os ponteiros e o operador de
    indireção `*`.

.Execução da aplicação
....
include::{local}/passagem_por_referencia.out[]
....

(((protótipo da função)))

O *protótipo da função* `calculadora` é definido com duas
variáveis do tipo inteiro e dois ponteiros para inteiros como
parâmetros de entrada. Compare com o exemplo anterior (forma
incorreta).

A função `calculadora` continua sendo uma função sem retorno (como no
código anterior).  Entretanto, são também passados como parâmetros de
entrada os endereços de memória das variáveis `sub` e `soma` (i.e.,
`&sub` e `&soma`). Compare esse trecho do código com o exemplo
anterior (forma incorreta).

A implementação da função `calculadora` utilizar dois inteiros (`x` e
`y`) e dois ponteiros para inteiros como parâmetros de entrada (i.e.,
`ptr1` e `ptr2`), conforme foi definido no protótipo da função. Nesse
cenário, quando a função `calculadora` é chamada na linha, os
endereços de memória das variáveis `sub` e `soma` (i.e., `&sub` e
`&soma`) são armazenados nos ponteiros `ptr1` e `ptr2`. A partir desse
momento, é possível atualizar o conteúdo das variáveis `sub` e `soma`
usando `ptr1` e `ptr2`, utilizando o operador de indireção `*`
(<<sec_ponteiros_definicao>>).

[[fig_pilha_sub_soma_execucao]]
.Ilustração da execução do programa para o cálculo da subtração e soma de dois números inteiros.
image::images/cap3/pilha_sub_soma_execucao.eps[scaledwidth="80%"]

A <<fig_pilha_sub_soma_execucao>> ilustra a pilha de execução da forma
correta do programa usando ponteiros. Note que na
<<fig_pilha_sub_soma_execucao>>(c) que os ponteiros `ptr1` e `ptr2`
recebem os endereços de memória das variáveis `sub` e `soma`,
respectivamente. Com isso, agora é possível alterar o conteúdo de
`sub` e `soma` usando esses ponteiros, mesmo dentro de uma função em
que `sub` e `soma` não são definidas. Isso é mostrado na
<<fig_pilha_sub_soma_execucao>>(d), observe que os ponteiros são
utilizados para se computar a subtração e soma. A
<<fig_pilha_sub_soma_execucao>>(e) apresenta a situação da pilha após
a função `calculadora` ser executada. Veja que as variáveis locais
`x`, `y`, `*ptr1` e `*ptr2` são desempilhadas.

// Sempre terminar o arquivo com uma nova linha.

