== Alocação Dinâmica de Memória

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* Fazer alocação dinâmica de memória em programas em linguagem C e entender 
as suas vantagens com relação à alocação estática de memória.
____

==== 3.4.1 Contextualização

Até agora foi visto que ponteiros podem ser usados para guardar endereços de variáveis já existentes em um programa em C. As variáveis podem ser entendidas como um espaço de memória que é rotulado durante o processo de compilação do programa em C. Ou seja, é alocado um espaço de memória estático para as variáveis. Nesse caso, foi visto que os ponteiros fornecem apenas uma segunda forma de acesso às variáveis, pois recebem os endereços de memória onde essas variáveis foram criadas. 

Um ponto importante a ser notado é que durante a execução do programa em C, uma vez criadas, essas variáveis não podem ser mais apagadas da memória. Ou seja, os espaços de memória utilizados pelas variáveis, não podem ser liberados para uso por outras variáveis ou tipos de dados durante a execução desse programa. Esse tipo de alocação de memória é chamada alocação estática. Ou seja, esse espaço de memória alocado estaticamente fica reservado para a variável (ou outro tipo/estrutura de dados, como arrays, estruturas ou registros, dentre outros...) durante todo o tempo de execução do programa.

Outro ponto importante é que na alocação estática o programador deve saber a quantidade de memória que é preciso ser definida no programa. Todavia, há casos em que o programador não sabe, no momento em que está montando o programa, a quantidade de memória (ou de tipo/estrutura de dados) que o programa irá precisar. Ou seja, há casos em que a quantidade de memória necessária varia de acordo com a execução do próprio programa. Um exemplo é um programa que permite múltiplos documentos abertos ao mesmo tempo, como muitos processadores de texto. Nesse caso, o programa não estima quantos documentos o usuário irá abrir nem qual o tamanho de cada documento aberto. Faz-se então necessário estudar um mecanismo que permita a alocação de memória de acordo com a necessidade e durante a execução do próprio programa. Isso é o que se chama de alocação dinâmica de memória.

Nesse cenário, os ponteiros são nossos aliados e o seu verdadeiro poder está em apontar para memória não rotulada ou dinâmica, alocada durante a execução do programa, i.e., alocada dinamicamente. Para melhor entender o conceito de alocação dinâmica, é discutida três formas para reservar espaço de memória para o armazenamento de informações em um programa em C: i) usar variáveis globais e estáticas; ii) usar variáveis locais; iii) alocar memória dinamicamente.

No caso de uso de variáveis globais e estáticas, sabe-se que o espaço reservado de memória para a variável global existe enquanto o programa estiver em execução e só pode ser utilizado pela própria variável.

No segundo caso, i.e. uso de variáveis locais em funções, como já foi visto, o espaço de memória reservado para a variável só existe enquanto a função que declarou a variável está sendo executada. Quando a execução da função for concluída, esse espaço de memória está liberado para outros usos e, portanto, as informações armazenadas na variável são perdidas e não podem ser mais recuperadas no escopo do programa.

A terceira opção é requisitar ao sistema, durante a execução do programa, um espaço de memória de um determinado tamanho. Esse espaço alocado dinamicamente permanece reservado até que seja liberado pelo programa usando um comando específico que será visto adiante. Com isso, pode-se alocar dinamicamente um espaço de memória em uma função e acessá-lo em outra. Quando o espaço de memória é liberado, ele fica liberado para outros usos dentro de programa e não se pode mais acessá-lo. Como já foi discutida, uma vantagem dessa abordagem é que, em problemas nos quais o programador não sabe a dimensão ou espaço necessário dos tipos de dados que irá utilizar no programa, pode-se usar a alocação dinâmica de memória para alocar e liberar memória ao longo da execução de um programa.

A Fig. 3.7 ilustra um esquema didático do uso da memória RAM do computador pelo sistema operacional durante a execução de um programa. Quando um programa é executado, o seu código em linguagem de máquina é carregado na memória RAM. Há espaços reservados para gravação de variáveis globais e estáticas que possam existir nesse programa. O restante da memória livre pode ser utilizado pelas variáveis locais e pelas variáveis alocadas dinamicamente. Toda vez quem uma função for chamada, é reservado um espaço na pilha de execução para o armazenamento das variáveis locais da função. Lembre-se que, conforme debatido anteriormente, esse espaço é liberado quando a função acaba a sua execução. A parte da memória não utilizada pela pilha de execução pode ser usada para alocar memória dinamicamente. Caso a pilha de execução cresça além do espaço de memória livre ou a quantidade de memória a ser alocada dinamicamente seja maior que a memória livre, o programa para de funcionar. Mais adiante, será visto como se deve fazer para abordar o programa na situação de alocação de memória além do espaço disponível.

Fig. 3.7: Ilustração do uso da memória RAM do computador durante a execução de um programa.

==== 3.4.2 Alocação dinâmica de memória

A alocação dinâmica de memória é feita usando-se funções da biblioteca padrão `stdlib.h`. As funções básicas para alocar e liberar memória são a *((malloc))* e *((free))*, respectivamente. Como será visto adiante, é possível fazer também realocação dinâmica de memória usando o *((realloc))*, ou seja, dado que existe um espaço de memória alocado dinamicamente é possível realocar esse espaço de memória liberando parte do espaço de memória que não vai se utilizar no programa.

A função `malloc` recebe como parâmetro de entrada o número de bytes que se deseja alocar e retorna o endereço de memória onde inicia o bloco de memória alocada dinamicamente. O leitor já deve ter percebido que para se armazenar o endereço de memória retornado pela função `malloc` deve-se usar uma variável do tipo ponteiro. Dessa forma, o esquema de alocação de memória em C é uma relação entre o uso da função `malloc` e de ponteiros, além da função `free` como será visto adiante.

Como exemplo, considere o caso que deseja alocar dinamicamente um vetor com 20 elementos reais do tipo `float`. Nesse caso, os comandos em linguagem C seriam

  float *ptr;
  ptr = (float*) malloc (20*sizeof(float));

Em que ptr é um ponteiro que irá armazenar o valor retornado pela função malloc, note que é um ponteiro para um tipo float já que se trata de alocação de um vetor de tipos float. Conforme foi visto no Capítulo 1, o comando sizeof é utilizado para se computar a quantidade de bytes que um tipo de dado necessita para ser gravado na memória. Nesse caso, será alocado dinamicamente um espaço de memória equivalente a 20 variáveis do tipo float. Um último detalhe é que a parte (float*) é necessária porque a função malloc retorna ou não um ponteiro genérico para um tipo qualquer, sendo representado por void*. O (float*) é usado para transforma o ponteiro em ponteiro para float, visto que está se alocando memória para um tipo float. Algumas bibliotecas mais recentes de C não necessitam desse comando, fazendo a conversão do ponteiro automaticamente.

A Fig. 3.8 ilustra como é que ocorre na memória a execução desse trecho de código. Observe na Fig. 3.8a que após a execução do comando que cria o ponteiro, um espaço é alocado na pilha de execução para ptr. Na Fig. 3.8b, considerando que um float ocupa 8 bytes, é ilustrada a situação da memória após o comando ptr = (float*) malloc (20*sizeof(float)).  Perceba também que 160 bytes são alocados dinamicamente na memória e que ptr recebe o endereço de memória onde inicia o bloco de 160 bytes recém alocados, ou seja, *ptr=0x36FC07.

Fig. 3.8: Ilustração de alocação dinâmica de um vetor com 20 elementos do tipo float.

Pode acontecer a situação que não haja espaço suficiente de memória para a alocação que se deseja fazer. Nesse caso, a função malloc retorna um endereço nulo para o ponteiro, ou seja, é retornado NULL. Um código simples pode ser adicionado no programa para verificar se essa situação ocorre e abortar a execução do programa. Veja no exemplo a seguir que a função exit, a qual pertence à biblioteca stdlib.h, é utilizada para abortar o programa.

----
  ...
  float *ptr;
  ptr = (float*) malloc(20*sizeof(float));
  if(ptr==NULL){
    printf ("Não há memória suficiente para alocação. O programa será encerrado.");
    exit(1); // aborta o programa e retorna 1 para o sistema operacional
  }
  ...

----


Para liberar o espaço de memória alocado dinamicamente a função free é utilizada. Essa função recebe como parâmetro de entrada o ponteiro que indica o início do bloco de memória a ser liberada. No exemplo em questão, seria o ponteiro prt. Dessa forma, para liberar o espaço de memória do vetor de 20 elementos float usa-se o comando

  free(ptr);

Vale a pena mencionar que o espaço de memória que foi liberado, não pode ser mais acessado pelo programa. Porém, pode ser reutilizado para armazenar outras informações, inclusive para se fazer uma nova alocação dinâmica de memória. Outro ponto importante é que o sistema operacional do computador é quem faz o trabalho de alocação e gerenciamento de memória. O programador apenas informa por meio dos comandos no programa que deseja fazer uma alocação de memória.

TIP: A função free() não destrói o ponteiro que recebe como entrada. Portanto, esse ponteiro pode ser reaproveitado dentro do escopo do mesmo programa. A função free() apenas libera o espaço de memória que foi alocado dinamicamente no programa para que possa ser utilizado para armazenar outros dados.

[TIP]
====
Não se pode liberar o mesmo bloco de memória duas vezes. Ou seja, basta utiliza uma vez a função free() para cada bloco de memória.

----
float *ptr;
ptr = (float* ) malloc (20*sizeof(float));
. . .
free(ptr);
free(ptr); // comando incorreto
----
====

[CAUTION]
====
Não se pode usar free() para liberar memória criada com a declaração de variáveis.

----
int soma;
soma=80;
. . .
free(soma); // comando incorreto
----
=====

O código a seguir mostra que um ponteiro pode ser utilizado várias vezes para se alocar memória dinamicamente. O cuidado que o programador deve ter é liberar o espaço de memória alocado dinamicamente antes de fazer uma nova alocação usando o mesmo ponteiro. Outra observação importante é que quando esse código foi executado no computador do autor, o mesmo endereço de memória foi impresso nas 15 e 22. Ou seja, após a liberação do espaço de memória alocado dinamicamente (linha 17), o sistema operacional pode reutilizá-lo para outros fins, que nesse caso foi uma nova alocação dinâmica de memória (linha 18).

Por fim, é possível fazer uma realocação de um espaço de memória que foi alocado dinamicamente. Isso é feito usando a função realloc(). O protótipo da função é 

  void *realloc (void *ptr, tamanho do espaço a ser realocado);

No exemplo a seguir é feita uma realocação em que o espaço alocado passa de 20 para 25 tipos float. E depois de 25 para 12 tipos floats.

----
float *ptr = (float* ) malloc (20*sizeof(float));
. . . (sequência de comandos)
ptr = (float* ) realloc (ptr, 25*sizeof(float));
. . . (sequência de comandos)
      ptr = (float* ) realloc (ptr, 12*sizeof(float));
----

----
/* programa que usa o mesmo ponteiro para alocar memória dinamicamente em
duas situações diferentes*/
#include <stdio.h>
#include <stdlib.h>
int main(){
int *ptr; // declara um ponteiro para um inteiro
ptr = (int*) malloc(sizeof(int)); // aloca memória para um inteiro
if(ptr==NULL){
printf ("Não há memória suficiente para alocação. O programa será
encerrado.");
exit(1); /* aborta o programa e retorna 1 para o sistema
operacional */
}
*ptr=69; // coloca um valor lá
printf("Valor inteiro = %d \n", *ptr); // imprimi valor
printf("Localização na memória= %p \n\n", ptr); // imprimi endereço
// de memória
free(ptr); // o espaço de memória é liberado
ptr = (int*) malloc(sizeof(int)); // usa o mesmo ponteiro para alocar
// memória para outro inteiro
*ptr=45;
printf("Valor inteiro = %d \n", *ptr); // imprimi valor
printf("Localização na memoria= %p \n\n", ptr); // imprimi endereço de
// memória
free(ptr); // o espaço de memória é liberado novamente
system("pause");
return 0;
}

----

==== 3.4.3 Arrays dinâmicos
===== 3.4.3.1 Vetores dinâmicos

Na maioria das vezes reserva-se o uso de alocação dinâmica para os casos em que a dimensão do vetor é desconhecida. Quando se sabe a sua dimensão, é preferível usar vetores alocados estaticamente, visto que do ponto de vista de tempo de execução do programa, esse tipo de alocação de vetores é mais rápida. Um ponto importante é que caso o vetor seja definido dentro do escopo de uma função, então ele existirá quando essa função estiver sendo executada. Portanto, o programador deve atentar para a utilização de vetores dentro de funções.

Para alocar dinamicamente um vetor, pode-se usar o seguinte comando

  float *ptr;
  ptr = (float*) malloc(n*sizeof(float));

Em que ptr é um ponteiro que irá armazenar o valor retornado pela função malloc, note que ptr é um ponteiro para um tipo float já que se trata de alocação de um vetor de tipos float. n representa a dimensão do vetor. A seguir é dado um exemplo de como se utilizar um vetor dinâmico em um programa em C que calcula a soma de dois vetores.

----
/* programa que soma dois vetores usando alocação dinâmica*/
#include <stdio.h>
#include <stdlib.h>
int* soma_vet(int[], int[]);
int main(){
int i, *ptr1; // declara um inteiro e um ponteiro para inteiro
int va[8], vb[8]; // declara dois vetores de inteiros com 8 posições
for(i=0; i<8;i++){ // preenchendo os vetores va e vb
va[i]=i;
vb[i]=i+1; }
ptr1=soma_vet(va, vb); // chamando a função soma_vet
for(i=0; i<8; i++){ // imprimindo o vetor va
printf(" %d ", va[i]); }
printf("\n\n");
for(i=0; i<8; i++){ // imprimindo o vetor vb
printf(" %d ", vb[i]); }
printf("\n\n");
for(i=0; i<8; i++){ // imprimindo o vetor soma
printf(" %d ", ptr1[i]); }
printf("\n\n");
system("pause");
return 0;
}
int* soma_vet(int va[8], int vb[8]){
int *ptr2;
ptr2 = (int*) malloc(8*sizeof(int));
if(ptr2==NULL) {
printf ("Não há memória suficiente. O programa será encerrado. ");
exit(1); } // aborta o programa e retorna 1 para o sist. o peracional
for(int j=0; j<8; j++){
ptr2[j]= va[j] + vb[j]; }
return ptr2;
}
----

Note que há outras maneiras de se resolver o problema da soma de dois vetores. Esse  exemplo foi dado somente para ilustra o uso de alocação de um vetor dinamicamente. Veja que a alocação dinâmica de memória ocorreu no escopo da função soma_vet (linha 27). Como o vetor é de oito posições, foi alocado um espaço para oito números inteiros no comando da linha 27. O ponteiro ptr2 foi utilizado como marcador inicial do vetor para guardar a soma dos vetores va e vb. Um último detalhe é que o comando free(ptr2) não necessitou ser dado, já que após o comando de return na linha 33 o bloco de memória alocado será liberado automaticamente já que a função foi encerrada.

===== 3.4.3.2 Matrizes dinâmicas
Para se definir matrizes dinâmicas na linguagem C enfrenta-se a limitação de que na linguagem C só é permitida fazer alocação dinâmica de memória de estruturas unidimensionais, como é o caso de vetores. Como uma matriz é uma estrutura com duas dimensões (linhas e colunas), para fazer uma alocação dinâmica de uma matriz é preciso utilizar artifícios de programação utilizando vetores.

Por exemplo, partindo da ideia de que para se alocar uma matriz na memória é preciso ter espaço suficiente para seus elementos, pode-se utilizar um vetor para tal fim. O tamanho do vetor alocado dinamicamente seria determinado de acordo com as dimensões da matriz que se deseja alocar. A ideia, portanto, é transformar, do ponto de vista conceitual, a matriz em um vetor unidimensional. A seguir é apresentada uma maneira de fazer tal transformação.

Considere uma matriz com l linhas e c colunas, a qual pode ser representada na linguagem C como mtr[l][c]. É possível criar um vetor com l*c elementos, aqui chamado de vet[l*c], que representará a matriz mtr[l][c]. Para a correspondência entra a matriz e o vetor seja atendida, um elemento aij da matriz é mapeado no elemento k=i*c + j, em que c é o número de colunas da matriz, como foi definido no início desse parágrafo. Essa relação é utilizada para se encontra um elemento k do vetor vet[l*c], ou seja, o elemento vet[i*c + j]. A Fig. 3.9 mostra uma ilustração desse mapeamento de matriz em vetor. 

O ponto negativo dessa estratégia é que é preciso usar a notação vet[i*c + j] para acessar os elementos da matriz no vetor.

Fig. 3.9: Ilustração do mapeamento de uma matriz em um vetor.

Usando esse mapeamento, a alocação dinâmica de uma matriz recai no problema de alocação dinâmica de um vetor. De forma geral, se quisermos fazer a alocação dinâmica de uma matriz com l linha e c colunas para armazenar números reais, basta fazer como abaixo

  float *mtr; // ponteiro para guardar o endereço onde inicia a alocação
  mtr = (float*) malloc(l*c*sizeof(float)); // note que foram alocados l*c elementos

O exemplo a seguir mostra o uso dessa estratégia para uma matriz com 4 linhas e 3 colunas.

----
/* programa que usa um vetor para alocar dinamicamente uma matriz */
#include <stdio.h>
#include <stdlib.h>
int main(){
int i, *ptr1; // declara um inteiro e um ponteiro para inteiro
int va[8], vb[8]; // declara dois vetores de inteiros com 8 posições
int l=4, c=3; // declara dois inteiros, i.e., as linhas e colunas da matriz
int i, j; // declara dois inteiros para serem os índices dos 'for'
float *mtr; // declara dois floats e um ponteiro para float
mtr = (float*) malloc(c*l*sizeof(float)); // alocação dinâmica de memória
if(mtr==NULL){
printf("Memoria insuficiente para alocar os c*l elementos. ");
return 1;
}
// preenchendo o vetor (diretamente) e a matriz (indiretamente)
for(i=0; i<l;i++){
for(j=0; j<c; j++){
mtr[i*c + j]= (9*i+j)/4.0;
}
}
// imprimindo a matriz
for (i=0;i<l;i++){
for (j=0;j<c;j++){
printf (" %0.1f", mtr[i*c + j]);
}
printf (" \n\n");
}
printf("\n\n");
free(mtr); // libera do espaço de memória alocado d inamicamente
system("pause");
return 0;
}

----

Como comentário final, existem outras maneiras de se alocar dinamicamente uma matriz, todavia, em geral, é preciso utilizar um vetor como estrutura auxiliar para representar a matriz.

===== 3.4.4 Registros (estruturas) dinâmicas

É possível também alocar dinamicamente um registro ou estrutura na linguagem C. Considere um registro definido como a seguir
      
      struct jogador {
           char nome[40];
           float salario;
           unsigned gols;
      };
      
      A alocação de registro dinamicamente segue a mesma lógica que já foi vista. Ou seja, deve-se inicialmente definir um ponteiro para o tipo de estrutura/tipo que se deseja alocar e em seguida usa-se a função malloc para fazer a alocação. Seguindo esse raciocínio, tem-se para o caso de um registro jogador
      
      struct jogador *ptr;
      ptr = (struct jogador*) malloc(sizeof(struct jogador));
      
Nesses dois comandos é alocado dinamicamente um registro do tipo jogador que é capaz de armazenar o nome do jogador com até 40 caracteres, o salário e o números de gols. O espaço de memória reservado é igual à soma do espaço dos campos pertencentes ao registro jogador. O comando sizeof(struct jogador), por sua vez, automaticamente passa para a função malloc a quantidade de memória necessária para alocar a estrutura jogador. Note que o programador não precisa se preocupar em computar a quantidade de memória necessária, como foi dito, isso é feito automaticamente pelo comando sizeof(struct jogador).

Um ponto importante a ser observado é que o operador para acessar os campos de um registro alocado dinamicamente é o ` -> ` e não o operador ponto `.`. O código a seguir ilustra a alocação dinâmica de registro e o preenchimento de seus campos. Perceba na linhas 12 e 13 que a alocação dinâmica do registro é feita, o preenchimento de seus campos é feitos nas linhas 16 a 18 e nas linhas 20 e 21 os valores gravados são impressos. Note que o operador ‘ -> ’ foi utilizado para acessar os campos do registro, tanto no preenchimento quanto na impressão. Na linha 22 a memória alocada é liberada usando o comando free(ptr).

----
/* programa que aloca dinamicamente um registro */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct jogador {
char nome[40];
float salario;
unsigned gols;
};
int main(){
struct jogador *ptr;// define um ponteiro para o registro 'jogador'
ptr = (struct jogador*) malloc(sizeof(struct jogador)); // aloca dinamicamente
// um registro do tipo jogador
// preenchendo o registro
strcpy(ptr->nome, "Tulipa Goleador ");
ptr->salario = 3000;
ptr->gols=2;
// imprimindo o registro
printf("Contratacao de %s com salario R$ %.1f e %u gols na temporada.
\n\n", ptr->nome, ptr->salario, ptr->gols);
free(ptr);
system("pause");
return 0;
}
----

É possível também definir vetores de registros, i.e., vetores cujos elementos são registros. Em outras palavras, em cada posição desse vetor é gravado um registro inteiro. A Fig. 3.10 mostra um vetor de registro para o caso da estrutura jogador definida no início dessa seção. Note que, como destacado na figura, em cada posição do vetor tem-se armazenado os campos definidos na estrutura jogador, ou seja, os campos nome, salario e gols.

Fig. 3.10: Ilustração de um vetor de estruturas.

Primeiramente, será mostrado como definir um vetor de estruturas para, se seguida apresentar como é feita a alocação dinâmica de um vetor de estruturas. Considerando a estrutura jogador, definida no início da seção, um vetor de estruturas pode ser definido da seguinte forma

  struct jogador Treze[22];

em que, struct é a palavra obrigatória na sintaxe do comando para especificar que trata-se de um registro ou estrutura, jogador é o tipo de registro que se pretende criar o vetor e Treze é o nome do vetor que acabou de ser criado. Observe que foi criado um vetor de estruturas com 22 posições.

O exemplo a seguir mostra um código para preenchimento de um de vetor de estruturas com 22 posições ilustrando o cadastramento de uma equipe de futebol com 22 jogadores. Note nas linhas 15 a 17 e 21 e 22 que o operador ponto ‘.’ é utilizado para acessar os campos do registro.


----
/* programa que preenche um vetor de registros */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct jogador {
char nome[40];
float salario;
unsigned gols;
};
int main(){
int i;
struct jogador Treze[22];
for (i=0;i<22;i++) {
printf("Digite o nome, salario e gols do jogador %d do Treze : \n", i+1);
scanf("%s", &Treze[i].nome);
scanf("%f", &Treze[i].salario);
scanf("%u", &Treze[i].gols);
}
printf("Time do Treze: \n");
for(i=0;i<22;i++){
printf("%s \n", Treze[i].nome);
printf("Com salario %0.1f \n", Treze[i].salario);
}
system("pause");
return 0;
}

----

A alocação de um vetor de registros dinamicamente segue a mesma lógica que já foi vista para um vetor de outros tipos (int, float, double, etc.). Ou seja, deve-se inicialmente definir um ponteiro para o tipo de estrutura/tipo que se deseja alocar e em seguida usa-se a função malloc para fazer a alocação dos espaços necessários que iram formar o vetor de registros. Seguindo esse raciocínio, tem-se para o caso de um registro jogador

  struct jogador *Treze;
  Treze = (struct jogador*) malloc(22*sizeof(struct jogador));

O exemplo a seguir é o mesmo código do exemplo anterior só que nesse caso o vetor de registros foi alocado dinamicamente. Note que na linha 25 o ponteiro Treze é liberado. Um detalhe de implementação é que o operador ponto ‘.’ foi utilizado para acessar os campos do vetor de registros pois a notação Treze[i] é a notação de vetor. Se a notação de ponteiro tivesse sido utilizada, ou seja (Treze + i), os campos seriam acessados usando-se o operador ‘->’ deveria ser usado. Assim, os campos seriam acessados por (Treze + i) ->nome, (Treze + i) ->salario e (Treze + i) ->gols.

----
/* programa que aloca dinamicamente e preenche um vetor de registros */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct jogador {
char nome[40];
float salario;
unsigned gols;
};
int main(){
int i;
struct jogador Treze[22];
for (i=0;i<22;i++){
printf("Digite o nome, salario e gols do jogador %d do Treze : \n", i+1);
scanf("%s", &Treze[i].nome);
scanf("%f", &Treze[i].salario);
scanf("%u", &Treze[i].gols);
}
printf("Time do Treze: \n");
for(i=0;i<22;i++){
printf("%s \n", Treze[i].nome);
printf("Com salario %0.1f \n", Treze[i].salario);
}
free(Treze);
system("pause");
return 0;
}

----

3.5 Exercícios propostos

1. Defina ponteiros e explique usando exemplos a função dos operadores de indireção `*` e de endereço `&`.

2. Considere o código a seguir. Quais valores serão impressos na tela?
+
----
#include <stdio.h>
#include <stdlib.h>
int main() {
int tot = 20;
int *ptr;
ptr = &tot;
printf(" %d.", tot);
printf(" %d“, *ptr);
*ptr = *ptr + tot;
printf(" %d“, tot);
*ptr = tot + 16;
printf(" %d“, tot);
system ("pause");
return 0;
}
----

3. Escreva os comandos em linguagem C que realizam as tarefas dadas nos itens (b), (c), (d) e (e). Considere que a variável V1 é do tipo double. O item (a) está resolvido para que o aluno melhor entenda o que se pede na questão.

a. Defina um ponteiro para double;
b. Atribua o endereço da variável V1 ao ponteiro para double definido na letra (a);
c. Imprima o endereço de memória da variável V1;
d. Imprima o endereço de memória armazenado no ponteiro da letra (b);
e. Inicialize a variável V1 em 12,5 e depois modifique o seu valor para 30,4 usando o ponteiro da letra (b).
+
....
  (a) Solução:
    double *ptr;
....

4. Faça um programa em C para calcular a área de um retângulo. O programa deve solicitar ao usuário os dois lados do retângulo. Você deve fazer duas versões desse programa: 

.. usando uma função com passagem por valor para calcular a área do retângulo; 
.. usando uma função com passagem por referência para calcular a área do retângulo.
+
Para cada caso faça/desenhe a pilha de execução do programa.

. Elabore um programa em C que receba três valores (obrigatoriamente maiores do que zero), representando as medidas dos três lados de um triângulo. Além da função main, o programa deve conter outra função para: i) determinar se esses lados formam um triângulo; ii) determinar e mostrar o tipo de triângulo (equilátero, isósceles ou escaleno), caso as medidas formem um triângulo. Na solução deve-se usar passagem de parâmetros por referência.
+
[TIP]
====
..Sabe-se que para ser triângulo, a medida de um lado qualquer deve ser inferior ou igual à soma das medidas dos outros dois lados. 
..Triângulo equilátero possui todos os lados iguais; triângulo isósceles possui pelo menos dois lados de medidas iguais; triângulo escaleno possui as medidas dos três lados diferentes.
====

. Considere uma equação de movimento para calcular a posição (s) e velocidade (v) de uma partícula em um determinado instante t, dado sua aceleração a, posição s0 e velocidade v0. O programa abaixo ilustra o uso dessa equação, imprimindo os valores 55.5 e 25.0, que representam a posição e velocidade calculadas para os valores utilizados pelo programa.
+
----
#include <stdio.h>
#include <stdlib.h>
int main(){
float s0=3.0, v0=10.0, a = 5.0, t = 3.0;
float s, v;
movimento(s0, v0, a, t, &s, &v);
printf (“%f %f\n”, s, v);
system ("pause");
return 0;
}
----
+
Implemente a função movimento de tal forma que o exemplo acima funcione adequadamente. A solução deve funcionar para quaisquer valores de t, a, s0 e v0, não podendo ser particularizada para o programa acima. Para o cálculo da velocidade (v) use a equação v= v0 + a.t e da posição (s) use s= s0 + v0.t + (a.t2)/2.

. Considere o programa abaixo que possui uma função calculadora que serve para calcular soma (s) e o produto (p) de dois números reais (c e d). O programa abaixo ilustra o uso dessa função para quando os valores 2.5 e 3.9 são utilizados pelo programa. Implemente a função calculadora de tal forma que o código abaixo funcione adequadamente. A solução deve funcionar para quaisquer valores de c e d, não podendo ser particularizada para os valores usados no programa abaixo, i.e., c= 2.5 e d=3.9. Após montar o código, faça/desenhe a pilha de execução do programa para o caso quando c= 2.5 e d=3.9.


#include <stdio.h>
#include <stdlib.h>
int main(){
  float c=2.5, d=3.9, s, p;
  calculadora(c, d, &s, &p);
  printf (“%f %f\n”, s, p);
  system ("pause");
  return 0;
}


. Implemente uma função chamada calc_esfera, que calcule o volume e a área da superfície de uma esfera de raio r. Essa função deve obedecer ao protótipo:
+
....
void calc_esfera(float r, float *area, float *volume).
....
+
Em seguida, monte um programa que peça o raio da esfera ao usuário e calcule os valores da área e volume da esfera. Dica: a área e volume da esfera são calculados como area=4.π.r2, volume=(4.π.r3)/3.

. Explique a diferença entre alocação estática e dinâmica de memória, citando vantagens e dando exemplo de uso. Dê pelos menos cinco situações nas quais alocação dinâmica de memória se faz necessária. Na sua resposta, use as Figs. 3.7 e 3.8 para ilustrar a utilização da memória do computador em cada um dos esquemas de alocação.

. Explique dando exemplos de como funciona as funções malloc(), realloc() e free(). Faça uma pesquisa em livros, internet, etc..., e explique como funciona o comando calloc(), o qual não foi apresentado no texto desse capítulo.

. Um professor de uma disciplina deseja montar um programa em linguagem C que seja capaz de receber as médias dos alunos de uma turma. O programa deve gravar as médias em um vetor que é alocado dinamicamente e ao final é liberado. Para dar uma ajuda ao professor, faça um programa que atenda o que foi dito. O programa deve conter uma função ou subrotina que receba o vetor com as médias, o qual foi alocado dinamicamente no programa, e calcular e retornar: i) a média da turma; ii) quantos alunos foram aprovados por média; iii) quantos alunos estão na prova final.
Dica: Considere que o aluno é aprovado por média se media>=7,0. Se 3,5<media<7,0, o aluno estará na prova final.

. Considerando a estrutura
+
....
struct Ponto {
    int x;
    int y;
};
....
+
Para representar um ponto em uma grade 2D. Implemente um programa em C que contenha uma função ou sub-rotina que indique se um ponto p está localizado dentro ou fora de um retângulo. O retângulo é definido por seus vértices inferior esquerdo v1 e superior direito v2. A função deve retornar 1 caso o ponto esteja localizado dentro do retângulo e 0 caso contrário. Use alocação dinâmica de memória para alocar dinamicamente a estrutura Ponto. Essa função deve obedecer ao protótipo:
+
....
int dentroRet (struct Ponto* v1, struct Ponto* v2, struct Ponto* p).
....

. Considerando a estrutura Jogador definida na Seção 3.4.4, implemente um programa em C que preencha e imprima na tela todos os jogadores de todos os times de futebol do Campeonato Brasileiro da Série A. Considere que cada time possui 11 jogadores. Use alocação dinâmica de memória na sua solução.
+
[TIP]
====
Crie uma função ou sub-rotina no programa, algo como Cadastra_equipe, para cadastrar uma equipe de futebol. Você poderá utilizar essa função para cadastrar as 20 equipes de futebol do Campeonato Brasileiro da Série A. Faça o mesmo para a parte da impressão na tela.
====

. Discuta o conceito de registros dinâmicos, matrizes dinâmicas e vetores dinâmicos dando exemplos e fazendo comparações. Usando o método da Seção 3.4.3.2 para representar matrizes de duas dimensões, é possível representar matrizes com três dimensões? Justifique a sua resposta.

