== Alocação Dinâmica de Memória

:online: {gitrepo}/blob/master/livro/capitulos/code/cap4
:local: code/cap4
:img: images/cap4

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* Fazer alocação dinâmica de memória em programas em linguagem C 
e entender as suas vantagens com relação à alocação estática de 
memória.
____

Até agora foi visto que ponteiros podem ser usados para guardar 
endereços de variáveis já existentes em um programa em C. As 
variáveis podem ser entendidas como um espaço de memória que é 
rotulado durante o processo de compilação do programa em C. Ou 
seja, é alocado um espaço de memória *((estático))* para as variáveis. 
Nesse caso, foi visto que os ponteiros fornecem apenas uma segunda 
forma de acesso às variáveis, pois recebem os endereços de 
memória onde essas variáveis foram criadas. 

Um ponto importante a ser notado é que _durante a execução do 
programa em C_, uma vez criadas, essas variáveis não podem ser mais 
apagadas da memória. Ou seja, os espaços de memória utilizados 
pelas variáveis, não podem ser liberados para uso por outras 
variáveis ou tipos de dados durante a execução desse programa. 
Esse tipo de alocação de memória é chamada *((alocação estática))*. 
Ou seja, esse espaço de memória alocado estaticamente fica 
reservado para a variável (ou outro tipo/estrutura de dados, como 
arrays, estruturas ou registros, dentre outros...) durante todo o 
tempo de execução do programa.

Outro ponto importante é que na alocação estática o programador 
deve saber a quantidade de memória que é preciso ser definida no 
programa. Todavia, há casos em que o programador não sabe, no 
momento em que está montando o programa, a quantidade de memória 
(ou de tipo/estrutura de dados) que o programa irá precisar. Ou 
seja, há casos em que a quantidade de memória necessária varia de 
acordo com a execução do próprio programa. Um exemplo é um 
programa que permite múltiplos documentos abertos ao mesmo tempo, 
como muitos processadores de texto. Nesse caso, o programa não 
estima quantos documentos o usuário irá abrir nem qual o tamanho de 
cada documento aberto. Faz-se então necessário estudar um mecanismo 
que permita a alocação de memória de acordo com a necessidade e 
durante a execução do próprio programa. Isso é o que se chama de 
*((alocação dinâmica))* de memória.

Nesse cenário, os ponteiros são nossos aliados e o seu verdadeiro 
poder está em apontar para a (((memória dinâmica))) *memória não rotulada ou dinâmica*, 
alocada durante a execução do programa, i.e., alocada 
dinamicamente. Para melhor entender o conceito de alocação 
dinâmica, são discutidas três formas para reservar espaço de 
memória para o armazenamento de informações em um programa em C: 

Uso de variáveis globais e estáticas:: Sabe-se que o 
espaço reservado de memória para a variável global existe enquanto 
o programa estiver em execução e só pode ser utilizado pela 
própria variável.

Uso de variáveis locais em funções:: Como já 
foi visto, o espaço de memória reservado para a variável só 
existe enquanto a função que a declarou está sendo 
executada. Quando a execução da função for concluída, esse 
espaço de memória está liberado para outros usos e, portanto, as 
informações armazenadas na variável são perdidas e não podem ser 
mais recuperadas no escopo do programa.

Uso de alocação dinâmina:: A terceira opção é requisitar ao sistema, durante a execução do 
programa, um espaço de memória de tamanho determinado. Após concedido, esse 
espaço alocado dinamicamente permanece reservado até que seja 
liberado pelo programa, usando uma função específica que será visto 
adiante. Com isso, pode-se alocar dinamicamente um espaço de 
memória em uma função e acessá-lo em outra. Quando o espaço de 
memória é liberado, ele fica disponível para alocações futuras,
inclusive para outros processos, não devendo ser acessado novamente
após sua liberação. Como já foi discutida, uma 
vantagem dessa abordagem é que, em problemas nos quais o programador 
_não sabe_ a dimensão ou espaço necessário dos tipos de dados que 
irá utilizar no programa, pode-se usar a alocação dinâmica de 
memória para alocar e liberar memória ao longo da execução de um 
programa.

A <<fig_uso_ram>> ilustra um esquema didático do uso da memória RAM do 
computador pelo sistema operacional durante a execução de um 
programa. Quando um programa é executado, o seu código em linguagem 
de máquina é carregado na memória RAM. Há espaços reservados 
para gravação de variáveis globais e estáticas que possam existir 
nesse programa. O restante da memória livre pode ser utilizado pelas 
variáveis locais e pelas variáveis alocadas dinamicamente. Toda vez 
quem uma função for chamada, é reservado um espaço na pilha de 
execução para o armazenamento das variáveis locais da função. 
Lembre-se que, conforme debatido anteriormente, esse espaço é 
liberado quando a função acaba a sua execução. A parte da 
memória não utilizada pela pilha de execução pode ser usada para 
alocar memória dinamicamente. Caso a pilha de execução cresça 
além do espaço de memória livre ou a quantidade de memória a ser 
alocada dinamicamente seja maior que a memória livre, o programa 
para de funcionar. Mais adiante, será visto como se deve fazer para 
abordar o programa na situação de alocação de memória além do 
espaço disponível.

[[fig_uso_ram]]
.Ilustração do uso da memória RAM do computador durante a execução de um programa.
image::{img}/memoria-ram.eps[scaledwidth="30%"]

=== Alocação dinâmica de memória
(((Alocação dinâmica)))

A alocação dinâmica de memória é feita usando-se funções da 
biblioteca padrão <<stdlib_h>>. As funções básicas para alocar e 
liberar memória são a *((malloc))* e *((free))*, respectivamente. 
Como será visto adiante, é possível fazer também realocação 
dinâmica de memória usando o *((realloc))*, ou seja, dado que 
existe um espaço de memória alocado dinamicamente é possível 
realocar esse espaço de memória liberando parte do espaço de 
memória que não vai se utilizar no programa.

A função <<malloc>> recebe como parâmetro de entrada o número de 
bytes que se deseja alocar e retorna o endereço de memória onde 
inicia o bloco de memória alocada dinamicamente. O leitor já deve 
ter percebido que para se armazenar o endereço de memória retornado 
pela função `malloc` deve-se usar uma variável do tipo ponteiro. 
Dessa forma, o esquema de alocação de memória em C é uma 
relação entre o uso da função `malloc` e de ponteiros, além da 
função `free` como será visto adiante.

Como exemplo, considere o caso que deseja alocar dinamicamente um 
vetor com 20 elementos do tipo `float`. Nesse caso, os comandos 
em linguagem C seriam

[source,c]
----
float *ptr;
ptr = (float*) malloc (20*sizeof(float));
----

Em que `ptr` é um ponteiro que irá armazenar o valor retornado pela 
função `malloc`, note que é um ponteiro para um tipo `float` já que 
se trata de alocação de um vetor de tipos `float`. Conforme foi visto 
no Capítulo 1, o comando `sizeof` é utilizado para se computar a 
quantidade de bytes que um tipo de dado necessita para ser gravado na 
memória. Nesse caso, será alocado dinamicamente um espaço de 
memória equivalente a 20 variáveis do tipo `float`. Um último 
detalhe é que a parte `(float*)` é necessária porque a função 
`malloc` retorna ou não um ponteiro genérico para um tipo qualquer, 
sendo representado por `void*`. O `(float*)` é usado para transforma o 
ponteiro em ponteiro para `float`, visto que está se alocando memória 
para um tipo `float`. Algumas bibliotecas mais recentes de C não 
necessitam desse comando, fazendo a conversão do ponteiro 
automaticamente.

A <<fig_ptr_na_ram>> ilustra como é que ocorre na memória a execução desse 
trecho de código. Observe na <<fig_ptr_na_ram>>(a) que após a execução do 
comando que cria o ponteiro, um espaço é alocado na pilha de 
execução para `ptr`. Na <<fig_ptr_na_ram>>(b) , considerando que um `float` ocupa 8 
bytes, é ilustrada a situação da memória após o comando `ptr = 
(float*) malloc (20*sizeof(float))`.  Perceba também que 160 bytes 
são alocados dinamicamente na memória e que ptr recebe o endereço 
de memória onde inicia o bloco de 160 bytes recém alocados, ou 
seja, `*ptr=0x36FC07`.

[[fig_ptr_na_ram]]
.Ilustração de alocação dinâmica de um vetor com 20 elementos do tipo float.
image::images/cap4/ptr_alocado_na_ram.eps[scaledwidth="70%"]

Pode acontecer a situação que não haja espaço suficiente de 
memória para a alocação que se deseja fazer. Nesse caso, a 
função <<malloc>> retorna um endereço nulo para o ponteiro, ou seja, 
é retornado `NULL`. Um código simples pode ser adicionado no programa 
para verificar se essa situação ocorre e abortar a execução do 
programa. Veja no exemplo a seguir que a função <<exit>>, a qual 
pertence à biblioteca <<stdlib_h>>, é utilizada para abortar o programa.

[source,c]
----
  ...
  float *ptr;
  ptr = (float*) malloc(20*sizeof(float));
  if(ptr==NULL){
    printf ("Não há memória suficiente, o programa será encerrado.");
    exit(EXIT_FAILURE); // aborta o programa retornando erro
  }
  ...

----

Para liberar o espaço de memória alocado dinamicamente a função 
<<free>> é utilizada. Essa função recebe como parâmetro de entrada o 
ponteiro que indica o início do bloco de memória a ser liberada. No 
exemplo em questão, seria o ponteiro `prt`. Dessa forma, para liberar 
o espaço de memória do vetor de 20 elementos `float` usa-se o comando:

[source,c]
----
free(ptr);
----

Vale a pena mencionar que o espaço de memória que foi liberado, 
não pode ser mais acessado pelo programa. Porém, pode ser 
reutilizado para armazenar outras informações, inclusive para se 
fazer uma nova alocação dinâmica de memória. Outro ponto 
importante é que o sistema operacional do computador é quem faz o 
trabalho de alocação e gerenciamento de memória. O programador 
apenas informa por meio dos comandos no programa que deseja fazer uma 
alocação de memória.

TIP: A função <<free>> não destrói o ponteiro que recebe como
entrada. Portanto, esse ponteiro pode ser reaproveitado dentro do 
escopo do mesmo programa. A função `free()` apenas libera o espaço 
de memória que foi alocado dinamicamente no programa para que possa 
ser utilizado para armazenar outros dados.

[WARNING]
====
Não se pode liberar o mesmo bloco de memória duas vezes. Ou seja, 
basta utiliza uma vez a função `free()` para cada bloco de memória.

[source,c]
----
float *ptr;
ptr = (float* ) malloc (20*sizeof(float));
. . .
free(ptr);
free(ptr); // comando incorreto
----

Também não se pode usar `free()` para liberar memória criada com a 
declaração de variáveis.

[source,c]
----
int soma;
soma=80;
. . .
free(soma); // comando incorreto
----
=====

O código a seguir mostra que um ponteiro pode ser utilizado várias 
vezes para se alocar memória dinamicamente. O cuidado que o 
programador deve ter é liberar o espaço de memória alocado 
dinamicamente antes de fazer uma nova alocação usando o mesmo 
ponteiro. Outra observação importante é que quando esse código 
foi executado no computador do autor, o mesmo endereço de memória 
foi impresso nas linhas 15 e 23. Ou seja, após a liberação do espaço de 
memória alocado dinamicamente (linha 16), o sistema operacional pode 
reutilizá-lo para outros fins, que nesse caso foi uma nova 
alocação dinâmica de memória (linha 19).

.Código fonte
{online}/reutilizando_ponteiro.c[{local}/reutilizando_ponteiro.c]

[source, c, numbered]
.Reunitizando um ponteiro
----
include::{local}/reutilizando_ponteiro.c[]
----

.Saída da execução
....
include::{local}/reutilizando_ponteiro.out[]
....


// FIXME Remover referências aos números das linhas

Por fim, é possível fazer uma realocação de um espaço de 
memória que foi alocado dinamicamente. Isso é feito usando a 
função <<realloc>>. O protótipo da função é: 

[source,c]
----
void *realloc (void *ptr, tamanho do espaço a ser realocado);
----

No exemplo a seguir é feita uma realocação em que o espaço alocado
passa de 20 para 25 tipos `float`. E depois de 25 para 12 tipos
`floats`.

[source,c]
----
float *ptr = (float* ) malloc (20*sizeof(float));
// ... (sequência de comandos)
ptr = (float* ) realloc (ptr, 25*sizeof(float));
// ... (sequência de comandos)
ptr = (float* ) realloc (ptr, 12*sizeof(float));
----

=== Arrays dinâmicos

==== Vetores dinâmicos

Na maioria das vezes reserva-se o uso de alocação dinâmica para os 
casos em que a dimensão do vetor é desconhecida. 

[TIP]
Quando se sabe a dimenção de um vetor, é preferível usar vetores
alocados estaticamente, visto que do ponto de vista de tempo de
execução do programa, esse tipo de alocação de vetores é mais rápida.
Um ponto importante é que caso o vetor seja definido dentro do escopo
de uma função, então ele somente existirá enquanto a função estiver
sendo executada.  Portanto, o programador deve atentar para a
utilização de vetores dentro de funções.

Para alocar dinamicamente um vetor, pode-se usar o seguinte comando:

[source,c]
----
float *ptr;
ptr = (float*) malloc(n*sizeof(float));
----

Em que `ptr` é um ponteiro que irá armazenar o valor retornado pela 
função `malloc`, note que `ptr` é um ponteiro para um tipo `float` já 
que se trata de alocação de um vetor de tipos `float`, e `n` representa a 
dimensão do vetor. A seguir é dado um exemplo de como se utilizar 
um vetor dinâmico em um programa em C que calcula a soma de dois 
vetores.

.Código fonte
{online}/soma_vetores.c[{local}/soma_vetores.c]

[source, c, numbered]
.Programa que realiza soma de dois vetores
----
include::{local}/soma_vetores.c[]
----

.Saída da execução
....
include::{local}/soma_vetores.out[]
....

Note que há outras maneiras de se resolver o problema da soma de 
dois vetores. Esse exemplo foi dado somente para ilustrar o uso de 
alocação de um vetor dinamicamente. Veja que a alocação dinâmica 
de memória ocorreu no escopo da função `soma_vet` (linha 30). Como o 
vetor é de oito posições, foi alocado um espaço para oito 
números inteiros no comando da linha 30. O ponteiro `ptr2` foi 
utilizado como marcador inicial do vetor para guardar a soma dos 
vetores `va` e `vb`. Um último detalhe é que o comando `free(ptr2)` não 
necessitou ser dado, já que após o comando de `return` na linha 38 o 
bloco de memória alocado será liberado automaticamente já que a 
função foi encerrada.

// TODO: Remover a referencia a linha de código

[[sec_matriz_dinamica]]
==== Matrizes dinâmicas
Para se definir matrizes dinâmicas na linguagem C enfrenta-se a 
limitação de que na linguagem C só é permitida fazer alocação 
dinâmica de memória de estruturas unidimensionais, como é o caso 
de vetores. Como uma matriz é uma estrutura com duas dimensões 
(linhas e colunas), para fazer uma alocação dinâmica de uma matriz 
é preciso utilizar artifícios de programação utilizando vetores.

Por exemplo, partindo da ideia de que para se alocar uma matriz na 
memória é preciso ter espaço suficiente para seus elementos, 
pode-se utilizar um vetor para tal fim. O tamanho do vetor alocado 
dinamicamente seria determinado de acordo com as dimensões da matriz 
que se deseja alocar. A ideia, portanto, é transformar, do ponto de 
vista conceitual, a matriz em um vetor unidimensional. A seguir é 
apresentada uma maneira de fazer tal transformação.

Considere uma matriz com `l` linhas e `c` colunas, a qual pode ser 
representada na linguagem C como `mtr[l][c]`. É possível criar um 
vetor com `l*c` elementos, aqui chamado de `vet[l*c]`, que representará 
a matriz `mtr[l][c]`. Para a correspondência entre a matriz e o vetor 
seja atendida, um elemento a~ij~ da matriz é mapeado no elemento
`k=i*c+j`, em que `c` é o número de colunas da matriz, como foi definido no 
início desse parágrafo. Essa relação é utilizada para se 
encontrar um elemento `k` do vetor `vet[l*c]`, ou seja, o elemento
`vet[i*c+j]`. A <<fig_matriz_no_vetor>> mostra uma ilustração desse mapeamento de matriz 
em vetor. 

O ponto negativo dessa estratégia é que é preciso usar a notação 
`vet[i*c + j]` para acessar os elementos da matriz no vetor.

[[fig_matriz_no_vetor]]
.Ilustração do mapeamento de uma matriz em um vetor.
image::images/cap4/matriz_em_vetor.eps[scaledwidth="100%"]

Usando esse mapeamento, a alocação dinâmica de uma matriz recai no 
problema de alocação dinâmica de um vetor. De forma geral, se 
quisermos fazer a alocação dinâmica de uma matriz com l linha e c 
colunas para armazenar números reais, basta fazer como se segue:

[source,c]
----
// ponteiro para guardar o endereço onde inicia a alocação
float *mtr;
// note que foram alocados l*c elementos
mtr = (float*) malloc(l*c*sizeof(float)); 
----

O exemplo a seguir mostra o uso dessa estratégia para uma matriz com 
4 linhas e 3 colunas.

.Código fonte
{online}/vetor_matriz.c[{local}/vetor_matriz.c]

[source, c]
.Utilizando vetor e matriz
----
include::{local}/vetor_matriz.c[]
----

.Saída da execução
....
include::{local}/vetor_matriz.out[]
....

Como comentário final, existem outras maneiras de se alocar 
dinamicamente uma matriz, todavia, em geral, é preciso utilizar um 
vetor como estrutura auxiliar para representar a matriz.

==== Registros (estruturas) dinâmicas

É possível também alocar dinamicamente um registro ou estrutura na 
linguagem C. Considere um registro definido como a seguir:

.Tipo estrutura jogador
[[code_tipo_jogador]]
[source,c]
----
typedef struct jogador_ {
  char nome[40];
  float salario;
  unsigned gols;
} jogador;
----

A alocação de registro dinamicamente segue a mesma lógica 
que já foi vista. Ou seja, deve-se inicialmente definir um ponteiro 
para o tipo de estrutura/tipo que se deseja alocar e em seguida 
usa-se a função `malloc` para fazer a alocação. Seguindo esse 
raciocínio, tem-se para o caso de um registro `jogador`:

// TODO não seria melhor declarar registro Jogador?

[source,c]
----
jogador *ptr;
ptr = (jogador*) malloc(sizeof(jogador));
----
      
Nesses dois comandos é alocado dinamicamente um registro do tipo 
`jogador` que é capaz de armazenar o nome do jogador com até 40 
caracteres, o salário e o números de gols. O espaço de memória 
reservado é igual à soma do espaço dos campos pertencentes ao 
registro `jogador`. O comando `sizeof(jogador)`, por sua vez, 
automaticamente passa para a função `malloc` a quantidade de bytes 
necessários para alocar a estrutura `jogador`. Note que o programador 
não precisa se preocupar em computar a quantidade de memória 
necessária, como foi dito, isso é feito automaticamente pelo 
comando `sizeof(jogador)`.

Um ponto importante a ser observado é que o operador para acessar os 
campos de um registro alocado dinamicamente é o `->` e não o 
operador ponto (``.''). O código a seguir ilustra a alocação dinâmica 
de registro e o preenchimento de seus campos. Perceba na linhas 12 e 
13 que a alocação dinâmica do registro é feita, o preenchimento 
de seus campos é feitos nas linhas 16 a 18 e nas linhas 20 e 21 os 
valores gravados são impressos. Note que o operador `->` foi 
utilizado para acessar os campos do registro, tanto no preenchimento 
quanto na impressão. Na linha 22 a memória alocada é liberada 
usando o comando `free(ptr)`.

.Código fonte
{online}/aloca_registro_dinamicamente.c[{local}/aloca_registro_dinamicamente.c]

[source, c]
.Programa que demonstra aloção de registro dinamicamente
----
include::{local}/aloca_registro_dinamicamente.c[]
----

.Saída da execução
....
include::{local}/aloca_registro_dinamicamente.out[]
....

É possível também definir vetores de registros, i.e., vetores 
cujos elementos são registros. Em outras palavras, em cada posição 
desse vetor é gravado um registro inteiro. A <<fig_vetor_de_registros>> mostra um 
vetor de registro para o caso da estrutura `jogador` definida no 
início dessa seção. Note que, como destacado na figura, em cada 
posição do vetor tem-se armazenado os campos definidos na estrutura 
`jogador`, ou seja, os campos `nome`, `salario` e `gols`.

[[fig_vetor_de_registros]]
.Ilustração de um vetor de estruturas.
image::{img}/vetor_de_registros.eps[scaledwidth="50%"]

Primeiramente, será mostrado como definir um vetor de estruturas 
para, em seguida apresentar como é feita a alocação dinâmica de 
um vetor de estruturas. Considerando a estrutura `jogador`, definida no 
início da seção, um vetor de estruturas pode ser definido da 
seguinte forma:

[source,c]
----
jogador jogadores[22];
----

Em que, `struct` é a palavra obrigatória na sintaxe do comando para 
especificar que trata-se de um registro ou estrutura, `jogador` é o 
tipo de registro que se pretende criar o vetor e `Treze` é o nome do 
vetor que acabou de ser criado. Observe que foi criado um vetor de 
estruturas com 22 posições.

O exemplo a seguir mostra um código para preenchimento de um  
vetor de estruturas com 22 posições ilustrando o cadastramento de 
uma equipe de futebol com 22 jogadores. Note nas linhas 16 a 19 e 22 
que o operador ponto ``.'' é utilizado para acessar os campos 
do registro.

.Código fonte
{online}/registros_estaticos.c[{local}/registros_estaticos.c]

[source, c]
.Utilização de registros estáticos
----
include::{local}/registros_estaticos.c[]
----

A alocação de um vetor de registros dinamicamente segue a mesma 
lógica que já foi vista para um vetor de outros tipos (`int`, `float`, 
`double`, etc.). Ou seja, deve-se inicialmente definir um ponteiro para 
o tipo de estrutura/tipo que se deseja alocar e em seguida usa-se a 
função `malloc` para fazer a alocação dos espaços necessários que 
iram formar o vetor de registros. Seguindo esse raciocínio, tem-se 
para o caso de um registro `jogador`:

[source,c]
----
jogador *jogadores;
jogadores = (jogador*) malloc(22*sizeof(jogador));
----

O exemplo a seguir temos um código semelhante ao anterior só que 
nesse caso o vetor de registros foi alocado dinamicamente. Note que 
na linha 32 o ponteiro `jogadores` é liberado. Um detalhe de 
implementação é que o operador ponto ``.'' foi utilizado para 
acessar os campos do vetor de registros pois a notação `jogadores[i]` é 
a notação de vetor. A notação de ponteiro foi demonstrada na linha 30.

.Código fonte
{online}/registro_dinamico.c[{local}/registro_dinamico.c]

[[code_regitro_dinamico]]
[source, c]
.Utilização de registros alocados dinamicamente
----
include::{local}/registro_dinamico.c[]
----



////
Sempre terminar o arquivo com uma nova linha.
////

