== Arquivos

:online: {gitrepo}/blob/master/livro/capitulos/code/cap5
:local: code/cap5

.Objetivos do capítulo
____

// FIXME atualizar objetivos
Ao final deste capítulo você deverá ser capaz de:

* Entender o conceito de arquivos e seus tipos;
* Aprofundar o conhecimento sobre armazenamento e manipulação de dados
  no computador por meio do uso de arquivos;
* Fazer manipulação de dados em arquivos por meio de operações como
  leitura, escrita, dentre outras.  

____


Até agora foi visto como é possível gravar e acessar informações/dados
na memória primária/principal do computador (também chamada memória
RAM). Para isso, foi visto que o uso de ponteiros é fundamental. O
problema dessa abordagem é que as informações/dados de um programa em
C gravadas na memória RAM são perdidas após o término da execução
desse programa. Ou seja, não se pode mais acessá-las ou recuperá-las.
Como fazer para, após a execução de um programa em C, ter acesso a
dados/informações manipuladas nesse programa? Uma solução é gravar
esses dados/informações em um arquivo na memória secundária do
computador (também chamado de Disco Rígido – Hard Disk drive). Nesse
caso, após a execução do programa em C, esses dados/informações
estarão disponíveis no arquivo gravado no disco rígido da máquina.

Nesse capítulo serão abordados conceitos básicos sobre arquivos e
formas de manipulação de dados no disco rígido na linguagem C, como
por exemplo, estratégias para salvar e recuperar dados/informações em
arquivos.

NOTE: Neste capítulo nós iremos direcioná-lo a consultar o padrão
<<c1x>> de C para conhecer a descrição das bibliotecas e funções que
iremos utilizar.

=== Os tipos de arquivos

Para compreender a utilização de arquivos em C precisamos conhecer os
diferentes tipos de arquivos que existem:

Arquivos somente-texto:: Estes arquivos possuem somente carácteres de
texto, exemplos deles são arquivos TXT, XML, HTML entre outros.  Outra
característica importante é que seu conteúdo costuma ser separado por
_quebras de linha_. Além disso, os sistemas operacionais codificam a
quebra de linha de forma diferente. Alguns aplicativos aceitam
entradas no formato somente-texto, causando erro de execução caso
encontre carácteres binários.

Arquivos binários:: Este arquivos possuem bytes que não representam
carácteres textuais, exemplos deles arquivos MP3, JPEG, ZIP etc.
O sistema operacional Windows requer que as funções de escrita e
leitura dos arquivos se comporte de forma diferente, de acordo com o
tipo de arquivo.

Arquivos especiais:: São arquivos que não armazenam conteúdo, veremos
este tipo nas próximas seções.

==== Arquivos especiais que representam dispositivos

Alguns arquivos podem representar dispositivos, de tal forma que
escrever ou ler nesses arquivos corresponde a enviar ou ler dados no
dispositivo.

Existem arquivos que representam os discos, partições, impressoras,
placa de rede, placa de som, microfone entre outros dispositivos.

Como exemplo da utilização deste tipo de arquivo especial, temos o
seguinte comando no Linux, que o ler do arquivo `/dev/cdrom` (que
representa o CD-ROM) e salva a imagem do CD-ROM no arquivo
`cdrom_image.iso`:

.Utilização do comando dd para criar uma imagem de cd
....
$ dd if=/dev/cdrom of=~/cdrom_image.iso
....

Neste comando o parâmetro `if` (_input file_) especifica o arquivo de
entrada, que neste caso é um arquivo especial que representa o CD-ROM
(`/dev/cdrom`).  Enquanto que `of` (_output file_) especifica o
arquivo de saída que será criado pela execução do comando `dd`:
`~/cdrom_image.iso`.

==== Arquivos especiais que criam um Pipe em memória

Um _Pipe_ é um recurso que possibilita dois processos transmitirem
dados entre eles. Enquanto um processo _produz_ bytes o segundo
_consome_ os bytes produzidos.

Você pode imaginar que o sistema operacional utiliza o arquivo para
criar meio de comunicação entre os dois processos, os bytes que forem
escritos no arquivo pelo primeiro processo estarão disponíveis para
leitura no segundo processo. O arquivo continua existindo antes e
depois da execução dos processos, no entanto ele não possui conteúdo
salvo no disco, diferente de um arquivo regular (não especial).

TIP: No <<cap_mkfifo>> demonstramos a criação e utilização deste tipo de
arquivo no Linux. Recomendamos esta leitura para conhecer a utilização
deste tipo de arquivo.

==== Arquivos especiais devido ao conteúdo

Alguns arquivos são especiais devido ao conteúdo que apresentam
durante sua leitura.

No Linux, quando lemos o arquivo `/proc/uptime` o sistema retorna
quanto tempo (em segundos) o sistema está ligado:

// Documentação sobbre /proc/uptime
// https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-proc-uptime.html

.Exibindo o conteúdo do arquivo /proc/uptime
....
$ cat /proc/uptime 
9913.84 38485.65
....

Neste caso podemos ver que o computador permaneceu ligado por
`9913.84` segundos, que equivale a aproximadamente  2,7
horas.footnote:[O segundo número é a soma da quantidade de segundos
que os _cores_ permaneceram ociosos.]


////
Também pensei em utilizar o seguinte exemplo, mas fiquei na dúvida se
/dev/urandom era especial por ser dispositivo ou pelo conteúdo:

Leitura de números aleatórios através de /dev/urandom

dd if=/dev/urandom of=saida.bin bs=1 count=4
od -t d1 saida.bin

////

=== Fluxo de dados

Para facilitar o aprendizado na utilização de arquivos em C precisamos
conhecer o conceito de fluxo de dados (_data stream_).

O áudio que escutamos numa rádio é exemplo de um _fluxo de dados_. 
As estações de rádio transmitem o fluxo e seu aparelho toca todos os
trechos que recebe. Uma vez sintonizado no fluxo, não há como pausar,
retroceder ou avançar nele, só é possível tocar o que está sendo
recebido.

O sistema de televisão também transmite as imagens através de fluxo,
no entanto, existes aparelhos que possibilitam pausar a programação. 
Neste caso o aparelho passa a gravar todo o conteúdo que continua
sendo recebido pelo fluxo em um Buffer, geralmente um disco interno.
Quando o usuário remove o pause, a programação é exibida a partir do
conteúdo salvo. Também é possível avançar no vídeo, mas somente até o
final do Buffer, quando atinge o ponto de recepção do fluxo novamente.

IMPORTANT: O fluxo diferencia de arquivo pois, no fluxo, não podemos
avançar ou retroceder na leitura. A leitura do fluxo costuma ser
sequencial, realizando o processamento dos dados logo após a leitura.
Como os arquivos possuem início e fim é possível determinar o seu
tamanho. Já os fluxos possuem início, mas nem todos possuem fim.

=== Arquivos

O principal propósito dos arquivos é salvar um conteúdo para ser
acessado futuramente. Para isso os arquivos possuem nomes e são
organizados em diretórios (ou pastas), para facilitar sua identificação. 

A organização dos nomes dos arquivos não é a mesma em todos os
sistemas operacionais. No Windows, por exemplo, existe um diretório
raiz por disco (`C:\`, `D:\` etc.) e os diretórios são separados pela
carácter ``\'' (_Contra barra_). Já no Unix, existe um único diretório
raiz `/` onde todos os demais diretórios são _descendentes_ dele, o
carácter separador de diretório é o ``/'' (_Barra_), diferente do
Windows.

Os arquivos somente texto também são diferentes, enquanto no Windows o
final de linha é codificado com dois carácteres, o Linux utiliza
apenas um.

=== Arquivos em C

IMPORTANT: A principal noção que precisamos ter em mente quando trabalhamos com
arquivos em C é que *fluxos e arquivos são manipulados com uma
interface única em C*.

O tipo de dado para manipular Arquivos e Streams é o `FILE`, definido
no cabeçalho <<stdio_h>>.

Na estrutura `FILE` são registradas todas as informações necessárias
para sua manipulação:

* Um indicador da posição no arquivo.
* Um ponteiro para seu Buffer (caso exista).
* Um indicador de erro, que registra caso houve algum erro de
  leitura/escrita.
* Um indicativo de _final de arquivo_, onde é registrado se o final do
  arquivo foi atingido.  

NOTE: Perceba que a estrutura `FILE` não possui registro do nome do
arquivo que está sendo manipulado.

=== Abrindo e Fechando arquivos em C

Toda vez que desejamos ler ou escrever num arquivo precisamos abrir o
arquivo indicando esta intenção.

==== Abrindo um arquivo

A abertura de arquivos em C é realizada através da função <<fopen>>,
que retorna um ponteiro `*FILE` caso a operação foi realizada com
sucesso ou `NULL` caso houve erro na abertura:

----
FILE* arquivo = fopen(nomeDoArquivo, modo); 
----

A intenção da abertura do arquivo deve ser especificada no parâmetro
`modo`:

r:: abre arquivo de texto para leitura
w:: abre arquivo de texto para escrita
wx:: cria arquivo de texto para escrita
a:: adiciona ao final; o indicador de posição de arquivo é
posicionado no final do arquivo
rb:: abre arquivo binário para leitura
wb:: abre arquivo binário para escrita
ab:: abre arquivo binário para escrita, no final do arquivo

Os códigos a seguir demonstram a abertura de arquivo para leitura de
um arquivo de texto e a abertura de um arquivo para escrita no formato
binário.

.Código fonte
{online}/abrindo_arquivo_de_texto.c[{local}/abrindo_arquivo_de_texto.c]

[source, c]
.Abrindo um arquivo de texto para leitura
----
include::{local}/abrindo_arquivo_de_texto.c[]
----


.Código fonte
{online}/abrindo_arquivo_de_texto.c[{local}/abrindo_arquivo_binario_para_escrita.c]

[source, c]
.Abrindo um arquivo binário para escrita
----
include::{local}/abrindo_arquivo_binario_para_escrita.c[]
----



=== Operações em arquivos

Independente do tipo de arquivo, as operações básicas que são
realizadas neles são:

- Abrir arquivo para leitura
- Escrever conteúdo no arquivo
- Ler conteúdo do arquivo 
- Fechar arquivo




["graphviz", scaledwidth="70%"]
----
include::../images/cap5/string.dot[]
----

=== Gravação de dados no disco rígido

A persistência de dados no disco é realizada através de
arquivos, que são organizados em diretórios (ou pastas) e apresentados
através de um ((Sistema de Arquivo)).  

A noção geral que temos de arquivo é que podemos salvar um conteúdo
em um arquivo e depois ler o conteúdo salvo. Com esta noção podemos
realizar atividades como: 

- Salvar um documento de texto em um arquivo, enviar para outra pessoa
  por e-mail.;
- Tocar um arquivo de música MP3 que foi gravado em algum estúdio;
- Assistir um vídeo que foi gravado por uma câmera;

No entanto, os arquivos também são utilizados como abstrações de
dispositivos em alguns sistemas de arquivos. Nestes 

Alguns sistemas operacionais existem arquivos especiais que são
utilizados como abstração de dispositivos. Escrever ou ler nesses
arquivos corresponde a enviar ou receber dados do dispositivo. 


=== Funções básicas para abrir e fechar arquivos na linguagem C
TODO.


=== Arquivos em modo texto
TODO.
==== Funções para leitura de dados em arquivos
TODO.


==== Funções para escrita de dados em arquivos
TODO.


==== Funções para manipulação de dados em arquivos texto
TODO.


=== Arquivos em modo binário
TODO.
==== Funções para leitura de dados em arquivos binários
TODO.

==== Funções para escrita de dados em arquivos binários
TODO.

==== Funções para manipulação de dados em arquivos binários
TODO.

=== Comparação entre arquivo em modo texto e binário
TODO.



////
Terminando arquivo com linha em branco
////

