[appendix]
[[cap_mkfifo]]
== Experimento com mkfifo para demonstrar arquivos especiais

Neste experimento iremos demonstrar a utilização do tipo de arquivo
especial _Named Pipe_, que pode ser utilizados para transmitir dados
entre dois aplicativos em execução no sistema operacional Linux.

=== Imprimindo na saída padrão

Para imprimir na saída padrão, vamos utilizar o comando
`cat` para ler linhas da entrada padrão e envia-las
para a saída padrão. Para sair, pressionamos `CTRL+D`
numa linha em branco. Para facilitar a identificação
das linhas, iremos invocar o comando com o parâmetro `-n`,
que irá numerar as linhas na saída:

.Invocando comando cat para imprimir linhas numeradas na saída padrão
....
$ cat -n
As linhas serão impressas na saída padrão,
     1	As linhas serão impressas na saída padrão,
que neste caso é a tela.
     2	que neste caso é a tela.
CTRL+D numa linha em branco para sair.
     3	CTRL+D numa linha em branco para sair.

....

Para direcionar a saída padrão para um arquivo, basta invocar o
comando `cat` direcionando a saída com `>`, indicando o arquivo de
destino:

.Redirecionando saída padrão para um arquivo
....
$ cat -n > saida.txt
Com a saída padrão direcionada para um arquivo
as linhas deixaram de serem impressas na tela.
Para encerrar pressionamos CTRL+D em nova linha
....

A invocação `cat` a seguir imprime o conteúdo do arquivo na saída
padrão, que neste caso foi a tela:

....
$ cat saida.txt
     1	Com a saída padrão direcionada para um arquivo
     2	as linhas deixaram de serem impressas na tela.
     3	Para encerrar pressionamos CTRL+D em nova linha
....

Na próxima seção, vamos aprender como criar um arquivo especial.

=== Criando um arquivo especial com mkfifo

O comando `mkfifo` cria um arquivo do tipo especial (_Named Piped_).
Todo o conteúdo que for escrito nele será mantido em um Buffer na
memória, até que outro processo leia do arquivo.

.Criando um arquivo especial com o mkfifo
....
$ mkfifo arquivo-especial.fifo
....

Vamos listar os arquivos para comparar os tamanhos:

.Verificando os tamanhos dos arquivos
....
$ du -ab
165	./saida.txt
0	./arquivo-especial.fifo
....

Percebam que o arquivo `saida.txt` ocupa 165 bytes, enquanto
`arquivo-especial.fifo` ocupa 0 byte. 

=== Utilizando o arquivo especial

Neste experimento vamos utilizar o arquivo especial criado para
possibilitar que dois processos transmitam dados entre si.

Vamos começar abrindo um terminal (`term1`) e utilizando o comando
`cat` para escrever conteúdo no arquivo:

.Primeiro terminal, enviando duas linhas para o buffer em memória
....
term1$ cat -n > arquivo-especial.fifo 
Primeira linha digitada
Segunda linha digitada

....

As linhas digitadas foram escritas no arquivo, no entanto, como ele é
um arquivo especial o sistema operacional está armazenando o que foi
escrito num Buffer em memória, aguardando que um outro aplicativo
_abra o arquivo para leitura_. O terminal não finaliza, fica
aguardando que novas linhas sejam digitadas.

NOTE: Percebam que caso houvesse algum erro no envio da primeira linha
para a saída, o `cat` encerraria e não seria possível digitar a
segunda linha.

Nosso próximo passo será abrir um novo terminal (`term2`), e tentar
ler o conteúdo do arquivo. Para isto invocamos o comando `cat`,
passando no nome do arquivo:

.Segundo terminal, utilizando o cat para ler do arquivo
....
term2$ cat arquivo-especial.fifo 
     1	Primeira linha digitada
     2	Segunda linha digitada

....

No segundo terminal o `cat` foi capaz de ler as linhas que foram
digitadas e salvas num buffer, antes de sua execução.  Ele também não
finaliza, permanece aberto, aguardando que novas linhas sejam
disponibilizadas através do arquivo.

NOTE: Como a segunda aplicação foi capaz de ler o que foi escrito
anteriormente pela primeira aplicação isto comprova que um Buffer
realmente existiu, guardando as duas linhas digitadas para leitura
posterior. 

Em seguida vamos digitar mais uma linha no primeiro terminal. Assim
que pressionamos `ENTER`, o segundo terminal recebe a linha digitada
pelo arquivo, demonstrando a conexão entre os dois processos:

.Primeiro terminal: digitando a terceira linha
....
term1$ cat -n > arquivo-especial.fifo 
Primeira linha digitada
Segunda linha digitada
Terceira linha digitada

....

.Segundo terminal: recebendo a terceira linha rapidamente
....
term2$ cat arquivo-especial.fifo 
     1	Primeira linha digitada
     2	Segunda linha digitada
     3	Terceira linha digitada

....

NOTE: No momento em que a segunda aplicação leu o conteúdo do Buffer,
ele deixou de existir. Tudo que for escrito no arquivo pelo primeiro
processo será direcionado para o segundo, que está lendo dele. Você
pode imaginar que ouve uma conexão entre os dois processos, como se
existisse um cano (_pipe_) ligando a saída de um processo na entrada
do outro.

Agora nós temos duas alternativas, finalizar a comunicação através do
primeiro terminal ou do segundo, vamos ver as duas opções:

Enviando o final do arquivo (`EOF`)::
Caso pressionarmos `CTRL+D` estaremos enviando o sinal de final de
arquivo, que finaliza a entrada do primeiro terminal e a leitura do
segundo. O resultado é o seguinte:
+
--
.Primeiro terminal: entrada finalizada enviando EOF
....
term1$ cat -n > arquivo-especial.fifo 
Primeira linha digitada
Segunda linha digitada
Terceira linha digitada
term1$
....

.Segundo terminal: finaliza após encontrar final do arquivo
....
term2$ cat arquivo-especial.fifo 
     1	Primeira linha digitada
     2	Segunda linha digitada
     3	Terceira linha digitada
$
....
--

Interrompendo a aplicação de leitura::
Quando interrompemos o segundo terminal com `CTRL+C` _a leitura do
arquivo é fechada_ e a aplicação é finalizada. A primeira aplicação, no
entanto, não sabe que a _conexão_ que o sistema operacional montou
entre os dois processos, através do arquivo especial, foi
interrompida. Ela continua aguardando que o usuário digite a próxima
linha. Quando uma nova linha for digitada, ela tentará escrever no
arquivo e não conseguirá, pois tanto a conexão como o Buffer
deixaram de existir:
+
--
.Finalizando o segundo terminal com CTRL+C
....
term2$ cat arquivo-especial.fifo
     1	Primeira linha digitada
     2	Segunda linha digitada
     3	Terceira linha digitada
^C
term2$
....

.Terminal finaliza tentando escrever no arquivo com conexão desfeita
....
term1$ cat -n > arquivo-especial.fifo 
Primeira linha digitada
Segunda linha digitada
Terceira linha digitada
Quarta linha digitada
~/temp/fifo$ 
....
--


IMPORTANT: Perceba que podemos abstrair que estamos utilizando um
arquivo e imaginar que estamos lendo ou escrevendo os dados em um
fluxo (_stream_) de entrada ou de saída. Poderemos ler dados do fluxo
até encontrar o final da fluxo (`EOF`). Na linguagem C os arquivos
(`FILE`) possuem esta mesma abstração.


// linha em branco

