Este livro é destinado a alunos de cursos como Ciência da Computação,
Sistemas de Informação, Engenharia da Computação e, sobretudo,
Licenciatura em Computação. Ele tem o objetivo de continuar o estudo
da Linguagem C, iniciado em disciplina anterior de Introdução a
Programação.

A primeira parte deste livro contém:

_Capítulo 1_:: Será realizada uma revisão dos conteúdos introdutórios
da Linguaguem C, que são pré-requisitos para os demais capítulos do
livro.
_Capítulo 2_:: Será apresentado o conceito de Registro e como
utilizá-lo na Linguagem C.
_Capítulo 3_:: Veremos a utilização de
Ponteiros e os tipos de passagem de parâmetros.
_Capítulo 4_::
Aprenderemos o que é Alocação Dinâmica de Memória e como realizá-la.
_Capítulo 5_:: Conheceremos os diferentes tipos de Arquivos e
aprenderemos como manipulá-los em C.

A segunda parte deste livro contém:

_Capítulo 6_:: Apresentação de todas as etapas do desenvolvimento do
projeto _lingua do i_, demonstrando a utilização de arquivos e testes
para guiar o desenvolvimento.
Apêndice A:: Demonstração da depuração
de uma aplicação com o `gdb`.
Apêndice B:: Experimento com `mkfifo`
para demonstrar a existência de arquivos especias.
Apêndice C::
Documentação das bibliotecas em C, utilizadas no livro.
Apêndice D::
Contém respostas de algumas atividades.
 



=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em
Computação, na modalidade à distância footnote::[Embora ele tenha sido
feito para atender aos alunos da Universidade Federal da Paraíba, o
seu uso não se restringe a esta universidade, podendo ser adotado por
outras universidades do sistema UAB.].  Ele foi concebido para ser
utilizado numa disciplina de 'Linguagem de Programação I', no segundo
semestre do curso.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros
  integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

////
Sempre terminar o arquivo com uma nova linha.
////
