== Motivando alunos ao trabalhar com projetos financiados

Trazemos uma proposta de trabalho que consiste em buscar
manter os alunos motivados através da utilização de projetos com
financiamento em sala de aula.

=== As bases desta proposta

Esta proposta de trabalho foi concebida visando atender as Bases
Legais (<<cap_bases_legais>>) apresentadas anteriormente. 

=== Metodologia

. O aluno deve compreender a classe de problemas que o conteúdo da
  disciplina pretender abordar.
. O aluno deve identificar um destes problemas que está associado a 
sua realidade e buscar um edital de financiamento em que possa
submeter um projeto.
. O aluno deve elaborar um projeto de acordo com as exigências do
  edital.
. O aluno deve buscar formar um grupo para realização do projeto.
. Os tutores devem escolher quais projetos irão _apadrinhar_,
  acompanhando e/ou se envolvendo com o desenvolvimento do projeto.
. O aluno deve acordar com a equipe docente as evidências que precisam
  serem produzidas, durante a execução do projeto, para gerar a
  *Ficha de Avaliação do Projeto*, que também contém as datas
  para as entregas parciais.
. Durante a execução do projeto os alunos deverão fornecer, sempre que
  solicitado, a Planilha de Avaliação do Projeto devidamente
  preenchida  
. O professores e tutores devem avaliar os alunos com base nas
  evidências apresentadas.

=== Acordando evidências para a avaliação
xxx
=== Avaliação do aluno

xxx

=== Premissas

// http://developer.ubuntu.com/resources/programming-languages/c-and-c-plus-plus/
// http://www.codeblocks.org/

Instalar o codeblocks:
    
    sudo apt-get install codeblocks

Fazer um experimento, que ao descrevê-lo fique evidente o pensamento
empirista, adaptando o experimento para torná-lo empirista.

Pensar num experimento que possamos nos apropriar dos conhecimentos
de cálculo ou matemática elementar.

Fazer um programa em C para resolvê-lo.

Se o problema fizer parte do dia-a-dia dos alunos, melhor ainda.

Problema deve ser realizado por um grupo, no mínimo uma dupla.

Deverá demonstrar a utilização dos compiladores, do git para
compartilhar o código entre eles. Demonstrar a diferença de cultura de
cultura entre eles.


.Problemas
* Contrução de um problema para controlar as cadernetas


.Problemas que incomodam
* Não receber o salário em dia
* Receber informações em cima da hora, sobre assuntos que eram de
  conhecimento de todos. (Em outras palavras: ser o último a saber).
* Preenchimento de caderneta em papel, ao invés do digital
** Como incorporar assuntos de outras disciplinas?
** Metodologia do trabalho / Publicando um artigo com o projeto?
** Cálculo: Análise das notas? Das Presenças? Como utilizar funções?
Funções injetoras? função inversa? Limites? Continuidade? Derivada?
Reta tangente? Valor médio? Integral?
** Inglês: escrita do abstract? Escrita da documentação e aplicação em
ingles?
** Fundamentação Psicológica da Educação: Analisar o conhecimento
obtido durante o projeto pelos integrantes? Artigo?

Analisar as repercursões do uso do programa. Fases do desenvolvimento:
análise, desenvolvimento e deploy.

Projeto para analisar o dados dos alunos?
Utilizar o github para juntar os dados de forma distribuída.
Desenhar gráficos? Usar o `dot` ou outra ferramenta para desenho?

Google API?

=== CGI

www.boutell.com/cgic/
libcgic-dev

libcgic2
cgilib

libapache2-mod-fastcgi

libfcgi-dev (instalado) http://www.fastcgi.com/drupal/ Header files of FastCGI
programa: cgi-fcgi
libfcgi0ldbl

////
Sempre terminar o arquivo com uma nova linha.
////

