== Premiação de alunos
TODO: À fazer.
=== Contexto e perspectiva
Daniel é um novo coordenador regional de uma rede de escolas públicas, que
possui um sistema de notas informatizado. Daniel acredita que seus
alunos do terceiro ano podem ser motivados através da distribuição de
premios para os melhores alunos de cada turma. Daniel conversou com o
técnico responsável pelo sistema da sua rede de escolas e este lhe confirmou 
que conseguiria obter uma listagem com todos os alunos e suas
respectivas com médias. Com esta lista Daniel deseja obter os nomes
dos alunos que deseja premiar. 

Waleska e Luciano, alunos do curso de Licenciatura em Computação à
distância, se voluntariaram para atender a demanda do coordenador e estão
confiantes que conseguirão realizá-la. 

=== Objetivos de aprendizagem
TODO: À fazer.
=== Entendendo o problema

Para premiar seus alunos o coordenador da escola tem a sua dispoição . 
O diretor daniel 

=== Entendo os dados

TODO: À fazer.
=== Planejando execução do projeto
TODO: À fazer.
=== Planejando a estrutura dos dados
TODO: À fazer.
=== Executando o projeto
TODO: À fazer.
=== Deploy do projeto
TODO: À fazer.
=== Avaliando o projeto
TODO: À fazer.

