[[cap_respostas]]
== Respostas das atividades

Nesta capítulo apresentamos as respostas de algumas atividades.

NOTE: Você pode contribuir para elaboração desta seção enviando suas respostas.

TIP: Na sala de aula, nos fóruns e mensagens recomendamos a utilização do site https://gist.github.com para compartilhar códigos e tirar dúvidas sobre eles.

=== Capítulo 1

Sem respostas.

=== Capítulo 2


3d. Não existe resposta única. Nesta resposta optamos por criar dois
registros, um para organizar o *Agendamento* e outro para agrupar os campos do *Horário*. As tabelas a seguir mostram o resultado da análise.

[width="80%",cols="1,2,1m",frame="topbot",options="header"]
|====
^| Novo tipo ^| Campo ^| Tipo do campo
.5+^.^s| Compromisso
| codigo ★| Numérico
| titulo | Textual
| local | Textual
| horario | Horario
| detalhes | Textual
|====

Exemplos de outros campos que poderiam existir são: tipo do compromisso, recorrencia do compromisso, participantes, horario de termino etc.

No tipo de registro `Compromisso`, nossa primeira tentativa de definir um campo identificador foi de utilizar `titulo`, mas percebemos que poderia haver mais de um
compromisso com o mesmo título. Outro possível campo seria o `horario`, no entanto
é possível existir dois compromissos com o mesmo horário. Portanto criamos um campo `codigo` para identificar os registros.


[width="80%",cols="1,2,1m",frame="topbot",options="header"]
|====
^| Novo tipo ^| Campo ^| Tipo do campo
.5+^.^s| Horario
| ano ★| Numérico
| mes ★| Numérico
| dia ★| Numérico
| hora ★| Numérico
| minuto ★| Numérico
|====

No tipo `Horario` percebemos que todos os campos juntos identificam um registro. Caso dois registros possuam os mesmos valores então eles representam um mesmo `Horario`.

.Código fonte
{gitrepo}/blob/master/livro/capitulos/code/respostas/reg_compromisso.c[code/respostas/reg_compromisso.c]

[source, c]
.Tipos dos registros `Compromisso` e `Horario`.
----
include::code/respostas/reg_compromisso.c[]
----




