# Usa o padrão c1x: http://en.wikipedia.org/wiki/C11_%28C_standard_revision%29
CFLAGS=-Wall -g -std=c1x

all: calculo_das_medias imc_calculo supermercado reg_aluno_exemplo reg_ponto_exemplo reg_produto_exemplo reg_triangulo reg_infopessoal reg_atribuicao conta_bancaria ponto_proximo

clean:
	rm -f aluno alunos revisao calculo_das_medias imc_calculo supermercado reg_aluno_exemplo reg_ponto_exemplo reg_produto_exemplo reg_infopessoal reg_atribuicao conta_bancaria ponto_proximo

