CC=gcc
CFLAGS=-Wall -g -std=c1x

all: reutilizando_ponteiro soma_vetores vetor_matriz aloca_registro_dinamicamente registros_estaticos registro_dinamico

clean:
	rm -rf reutilizando_ponteiro soma_vetores vetor_matriz aloca_registro_dinamicamente registros_estaticos registro_dinamico

